{
 "title": "Erutan",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Observer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(observer_event[5m])", "legendFormat": "Events" }
   ]
  },
  {
   "title": "Animals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(herbivorous_eat)", "legendFormat": "Eat" },
    { "expr": "herbivorous_speed", "legendFormat": "Speed" },
    { "expr": "herbivorous_life", "legendFormat": "Life" },
    { "expr": "avg(herbivorous_reproduction)", "legendFormat": "Reproduction" },
    { "expr": "herbivorous_volume", "legendFormat": "Volume" }
   ]
  },
  {
   "title": "Collisions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(physics_collision[5m])", "legendFormat": "Collisions" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"erutan\"}[5m])",
     "legendFormat": "{{job}} cpu_seconds_total"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "physics_object", "legendFormat": "Objets" }
   ]
  },
  {
   "title": "gRPC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(grpc_server_msg_sent_total)",
     "legendFormat": "server_msg_sent_total"
    },
    {
     "expr": "avg(grpc_server_msg_received_total)",
     "legendFormat": "server_msg_received_total"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"erutan\"}",
     "legendFormat": "{{job}} - alloc_bytes"
    }
   ]
  }
 ]
}