# Server configurations
server:
  host: "127.0.0.1"
  port: 50051

logic:
  time_scale: 1
  octree_size: 100000
  ground_size: 50
  herbivorous:
    reproduction_threshold: 80
    reproduction_life_loss: 60
    eat_life_gain: 50
    life_loss_rate: 500
    quantity: 5
    life: 50
  initial_herbs: 20
  player:
    spawn:
      - 0
      - 20
      - 0
    culling: 5000

debug_mode: true
ssl: true
ssl_cert: server1.crt
ssl_key: server1.key
metrics_port: 34555
network_rate: 1 # lower = more packets
updates_rate: 0.0001 # ~50 fps, lower = more fps, more systems update
