// Code generated by protoc-gen-go. DO NOT EDIT.
// source: realtime.proto

package erutan

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type StreamRequest struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{4}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StreamResponse struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*StreamResponse_ClientLogin
	//	*StreamResponse_ClientLogout
	//	*StreamResponse_ClientMessage
	//	*StreamResponse_ServerMessage
	//	*StreamResponse_ServerShutdown
	Event                isStreamResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isStreamResponse_Event interface {
	isStreamResponse_Event()
}

type StreamResponse_ClientLogin struct {
	ClientLogin *StreamResponse_Login `protobuf:"bytes,2,opt,name=client_login,json=clientLogin,proto3,oneof"`
}

type StreamResponse_ClientLogout struct {
	ClientLogout *StreamResponse_Logout `protobuf:"bytes,3,opt,name=client_logout,json=clientLogout,proto3,oneof"`
}

type StreamResponse_ClientMessage struct {
	ClientMessage *StreamResponse_Message `protobuf:"bytes,4,opt,name=client_message,json=clientMessage,proto3,oneof"`
}

type StreamResponse_ServerMessage struct {
	ServerMessage *StreamResponse_Message `protobuf:"bytes,5,opt,name=server_message,json=serverMessage,proto3,oneof"`
}

type StreamResponse_ServerShutdown struct {
	ServerShutdown *StreamResponse_Shutdown `protobuf:"bytes,6,opt,name=server_shutdown,json=serverShutdown,proto3,oneof"`
}

func (*StreamResponse_ClientLogin) isStreamResponse_Event() {}

func (*StreamResponse_ClientLogout) isStreamResponse_Event() {}

func (*StreamResponse_ClientMessage) isStreamResponse_Event() {}

func (*StreamResponse_ServerMessage) isStreamResponse_Event() {}

func (*StreamResponse_ServerShutdown) isStreamResponse_Event() {}

func (m *StreamResponse) GetEvent() isStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamResponse) GetClientLogin() *StreamResponse_Login {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogin); ok {
		return x.ClientLogin
	}
	return nil
}

func (m *StreamResponse) GetClientLogout() *StreamResponse_Logout {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogout); ok {
		return x.ClientLogout
	}
	return nil
}

func (m *StreamResponse) GetClientMessage() *StreamResponse_Message {
	if x, ok := m.GetEvent().(*StreamResponse_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

func (m *StreamResponse) GetServerMessage() *StreamResponse_Message {
	if x, ok := m.GetEvent().(*StreamResponse_ServerMessage); ok {
		return x.ServerMessage
	}
	return nil
}

func (m *StreamResponse) GetServerShutdown() *StreamResponse_Shutdown {
	if x, ok := m.GetEvent().(*StreamResponse_ServerShutdown); ok {
		return x.ServerShutdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamResponse_ClientLogin)(nil),
		(*StreamResponse_ClientLogout)(nil),
		(*StreamResponse_ClientMessage)(nil),
		(*StreamResponse_ServerMessage)(nil),
		(*StreamResponse_ServerShutdown)(nil),
	}
}

type StreamResponse_Login struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Login) Reset()         { *m = StreamResponse_Login{} }
func (m *StreamResponse_Login) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Login) ProtoMessage()    {}
func (*StreamResponse_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 0}
}

func (m *StreamResponse_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Login.Unmarshal(m, b)
}
func (m *StreamResponse_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Login.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Login.Merge(m, src)
}
func (m *StreamResponse_Login) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Login.Size(m)
}
func (m *StreamResponse_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Login.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Login proto.InternalMessageInfo

func (m *StreamResponse_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamResponse_Logout struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Logout) Reset()         { *m = StreamResponse_Logout{} }
func (m *StreamResponse_Logout) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Logout) ProtoMessage()    {}
func (*StreamResponse_Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 1}
}

func (m *StreamResponse_Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Logout.Unmarshal(m, b)
}
func (m *StreamResponse_Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Logout.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Logout.Merge(m, src)
}
func (m *StreamResponse_Logout) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Logout.Size(m)
}
func (m *StreamResponse_Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Logout proto.InternalMessageInfo

func (m *StreamResponse_Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamResponse_Message struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Message) Reset()         { *m = StreamResponse_Message{} }
func (m *StreamResponse_Message) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Message) ProtoMessage()    {}
func (*StreamResponse_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 2}
}

func (m *StreamResponse_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Message.Unmarshal(m, b)
}
func (m *StreamResponse_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Message.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Message.Merge(m, src)
}
func (m *StreamResponse_Message) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Message.Size(m)
}
func (m *StreamResponse_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Message.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Message proto.InternalMessageInfo

func (m *StreamResponse_Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamResponse_Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StreamResponse_Packet struct {
	// Types that are valid to be assigned to Type:
	//	*StreamResponse_Packet_Position_
	Type                 isStreamResponse_Packet_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StreamResponse_Packet) Reset()         { *m = StreamResponse_Packet{} }
func (m *StreamResponse_Packet) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Packet) ProtoMessage()    {}
func (*StreamResponse_Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 3}
}

func (m *StreamResponse_Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Packet.Unmarshal(m, b)
}
func (m *StreamResponse_Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Packet.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Packet.Merge(m, src)
}
func (m *StreamResponse_Packet) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Packet.Size(m)
}
func (m *StreamResponse_Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Packet proto.InternalMessageInfo

type isStreamResponse_Packet_Type interface {
	isStreamResponse_Packet_Type()
}

type StreamResponse_Packet_Position_ struct {
	Position *StreamResponse_Packet_Position `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

func (*StreamResponse_Packet_Position_) isStreamResponse_Packet_Type() {}

func (m *StreamResponse_Packet) GetType() isStreamResponse_Packet_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StreamResponse_Packet) GetPosition() *StreamResponse_Packet_Position {
	if x, ok := m.GetType().(*StreamResponse_Packet_Position_); ok {
		return x.Position
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamResponse_Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamResponse_Packet_Position_)(nil),
	}
}

type StreamResponse_Packet_Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Packet_Position) Reset()         { *m = StreamResponse_Packet_Position{} }
func (m *StreamResponse_Packet_Position) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Packet_Position) ProtoMessage()    {}
func (*StreamResponse_Packet_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 3, 0}
}

func (m *StreamResponse_Packet_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Packet_Position.Unmarshal(m, b)
}
func (m *StreamResponse_Packet_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Packet_Position.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Packet_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Packet_Position.Merge(m, src)
}
func (m *StreamResponse_Packet_Position) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Packet_Position.Size(m)
}
func (m *StreamResponse_Packet_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Packet_Position.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Packet_Position proto.InternalMessageInfo

func (m *StreamResponse_Packet_Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *StreamResponse_Packet_Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *StreamResponse_Packet_Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type StreamResponse_Shutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse_Shutdown) Reset()         { *m = StreamResponse_Shutdown{} }
func (m *StreamResponse_Shutdown) String() string { return proto.CompactTextString(m) }
func (*StreamResponse_Shutdown) ProtoMessage()    {}
func (*StreamResponse_Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbdca058206953b, []int{5, 4}
}

func (m *StreamResponse_Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse_Shutdown.Unmarshal(m, b)
}
func (m *StreamResponse_Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse_Shutdown.Marshal(b, m, deterministic)
}
func (m *StreamResponse_Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse_Shutdown.Merge(m, src)
}
func (m *StreamResponse_Shutdown) XXX_Size() int {
	return xxx_messageInfo_StreamResponse_Shutdown.Size(m)
}
func (m *StreamResponse_Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse_Shutdown proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "erutan.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "erutan.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "erutan.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "erutan.LogoutResponse")
	proto.RegisterType((*StreamRequest)(nil), "erutan.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "erutan.StreamResponse")
	proto.RegisterType((*StreamResponse_Login)(nil), "erutan.StreamResponse.Login")
	proto.RegisterType((*StreamResponse_Logout)(nil), "erutan.StreamResponse.Logout")
	proto.RegisterType((*StreamResponse_Message)(nil), "erutan.StreamResponse.Message")
	proto.RegisterType((*StreamResponse_Packet)(nil), "erutan.StreamResponse.Packet")
	proto.RegisterType((*StreamResponse_Packet_Position)(nil), "erutan.StreamResponse.Packet.Position")
	proto.RegisterType((*StreamResponse_Shutdown)(nil), "erutan.StreamResponse.Shutdown")
}

func init() { proto.RegisterFile("realtime.proto", fileDescriptor_dcbdca058206953b) }

var fileDescriptor_dcbdca058206953b = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xf5, 0x86, 0xc4, 0x49, 0x27, 0x17, 0xd0, 0xaa, 0x54, 0xd6, 0x52, 0x28, 0xb2, 0x04, 0x2a,
	0x2f, 0x2e, 0x0a, 0x88, 0xcb, 0x03, 0x48, 0x44, 0x45, 0x58, 0x08, 0xa4, 0x68, 0xcb, 0x3b, 0x72,
	0xd3, 0x25, 0x58, 0x8d, 0x77, 0x8d, 0x77, 0xdd, 0x36, 0xfd, 0x06, 0xbe, 0x88, 0x3f, 0xe0, 0xaf,
	0x90, 0xf7, 0x62, 0x37, 0x55, 0x2c, 0xf1, 0xb6, 0x33, 0x7b, 0xce, 0x99, 0x99, 0xa3, 0x19, 0x98,
	0x14, 0x2c, 0x59, 0xa9, 0x34, 0x63, 0x51, 0x5e, 0x08, 0x25, 0xb0, 0xcf, 0x8a, 0x52, 0x25, 0x9c,
	0x1c, 0x2c, 0x85, 0x58, 0xae, 0xd8, 0x91, 0xce, 0x9e, 0x96, 0x3f, 0x8e, 0x2a, 0x8c, 0x54, 0x49,
	0x96, 0x1b, 0x60, 0xf8, 0x1e, 0x46, 0x5f, 0xc4, 0x32, 0xe5, 0x94, 0xfd, 0x2a, 0x99, 0x54, 0x98,
	0xc0, 0x20, 0x4f, 0xa4, 0xbc, 0x14, 0xc5, 0x59, 0x80, 0x1e, 0xa3, 0xc3, 0x1d, 0x5a, 0xc7, 0x18,
	0x43, 0x97, 0x27, 0x19, 0x0b, 0x3a, 0x3a, 0xaf, 0xdf, 0xe1, 0x13, 0x18, 0x5b, 0xbe, 0xcc, 0x05,
	0x97, 0x0c, 0xef, 0x42, 0x4f, 0x89, 0x73, 0xc6, 0x2d, 0xdb, 0x04, 0x16, 0x26, 0x4a, 0xe5, 0xea,
	0x6c, 0x87, 0xdd, 0x83, 0x89, 0x83, 0x19, 0xb9, 0xf0, 0x19, 0x8c, 0x4f, 0x54, 0xc1, 0x92, 0xcc,
	0x11, 0x03, 0xe8, 0x67, 0x4c, 0xca, 0x64, 0xe9, 0xfa, 0x70, 0x61, 0xf8, 0xb7, 0x07, 0x13, 0x87,
	0xb5, 0xcd, 0xbc, 0x81, 0x9d, 0x7a, 0x60, 0x5d, 0x69, 0x38, 0x25, 0x91, 0xb1, 0x24, 0x72, 0x96,
	0x44, 0xdf, 0x1c, 0x82, 0x36, 0x60, 0xfc, 0x01, 0x46, 0x8b, 0x55, 0xca, 0xb8, 0xfa, 0xbe, 0xaa,
	0xc6, 0xd3, 0xb5, 0x86, 0xd3, 0xfd, 0xc8, 0xf8, 0x1a, 0x6d, 0xd6, 0x89, 0xb4, 0x05, 0xb1, 0x47,
	0x87, 0x86, 0xa3, 0x43, 0x7c, 0x0c, 0xe3, 0x46, 0x42, 0x94, 0x2a, 0xb8, 0xa3, 0x35, 0x1e, 0xb6,
	0x6b, 0x88, 0x52, 0xc5, 0x1e, 0x1d, 0xd5, 0x22, 0xa2, 0x54, 0xf8, 0x13, 0x4c, 0xac, 0x8a, 0x1b,
	0xbb, 0xab, 0x65, 0x1e, 0xb5, 0xc8, 0x7c, 0x35, 0xa8, 0xd8, 0xa3, 0xb6, 0xba, 0x4d, 0x54, 0x42,
	0x92, 0x15, 0x17, 0xac, 0xa8, 0x85, 0x7a, 0xff, 0x2b, 0x64, 0x78, 0x4e, 0xe8, 0x33, 0xdc, 0xb5,
	0x42, 0xf2, 0x67, 0xa9, 0xce, 0xc4, 0x25, 0x0f, 0x7c, 0xad, 0x74, 0xd0, 0xa2, 0x74, 0x62, 0x61,
	0xb1, 0x47, 0x6d, 0x0b, 0x2e, 0x43, 0x1e, 0x40, 0xcf, 0x98, 0xe5, 0x76, 0x0b, 0x35, 0xbb, 0x45,
	0xf6, 0xc1, 0xb7, 0x26, 0x6c, 0xfb, 0x7d, 0x0d, 0x7d, 0xd7, 0xd1, 0x96, 0xef, 0xf6, 0x3d, 0x21,
	0xbf, 0x11, 0xf8, 0xf3, 0x64, 0x71, 0xce, 0x14, 0x3e, 0x86, 0x41, 0x2e, 0x64, 0xaa, 0x52, 0xc1,
	0xed, 0x7a, 0x3c, 0x6d, 0x99, 0xc1, 0x10, 0xa2, 0xb9, 0x45, 0xc7, 0x1e, 0xad, 0x99, 0xe4, 0x25,
	0x0c, 0x5c, 0x1e, 0x8f, 0x00, 0x5d, 0x69, 0xa9, 0x0e, 0x45, 0x57, 0x55, 0xb4, 0xd6, 0xe5, 0x3b,
	0x14, 0xad, 0xab, 0xe8, 0x5a, 0x2f, 0x41, 0x87, 0xa2, 0xeb, 0x99, 0x0f, 0x5d, 0xb5, 0xce, 0x19,
	0x01, 0x18, 0x38, 0x3b, 0x66, 0x7d, 0xe8, 0xb1, 0x0b, 0xc6, 0xd5, 0xf4, 0x0f, 0x02, 0xff, 0xa3,
	0x6e, 0x04, 0xbf, 0x72, 0x16, 0xed, 0xba, 0xd6, 0x6e, 0x1e, 0x2c, 0xb9, 0x7f, 0x2b, 0x6b, 0xef,
	0xc6, 0xc3, 0x6f, 0x6b, 0xf7, 0x6e, 0x42, 0x9a, 0x13, 0x24, 0x7b, 0xb7, 0xd3, 0x35, 0xf5, 0x1d,
	0xf8, 0x66, 0xfc, 0x86, 0xba, 0x71, 0x84, 0x0d, 0x75, 0xd3, 0xa5, 0xd0, 0x3b, 0x44, 0xcf, 0xd1,
	0x6c, 0x0f, 0x60, 0x21, 0x32, 0x0b, 0x99, 0xd9, 0x39, 0xe6, 0xe8, 0xd4, 0xd7, 0x27, 0xf7, 0xe2,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x2f, 0xb3, 0x5e, 0xad, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ErutanClient is the client API for Erutan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ErutanClient interface {
	//
	//Blabla
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error)
}

type erutanClient struct {
	cc *grpc.ClientConn
}

func NewErutanClient(cc *grpc.ClientConn) ErutanClient {
	return &erutanClient{cc}
}

func (c *erutanClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/erutan.Erutan/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erutanClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/erutan.Erutan/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erutanClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Erutan_serviceDesc.Streams[0], "/erutan.Erutan/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &erutanStreamClient{stream}
	return x, nil
}

type Erutan_StreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type erutanStreamClient struct {
	grpc.ClientStream
}

func (x *erutanStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *erutanStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ErutanServer is the server API for Erutan service.
type ErutanServer interface {
	//
	//Blabla
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Stream(Erutan_StreamServer) error
}

// UnimplementedErutanServer can be embedded to have forward compatible implementations.
type UnimplementedErutanServer struct {
}

func (*UnimplementedErutanServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedErutanServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedErutanServer) Stream(srv Erutan_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterErutanServer(s *grpc.Server, srv ErutanServer) {
	s.RegisterService(&_Erutan_serviceDesc, srv)
}

func _Erutan_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErutanServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erutan.Erutan/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErutanServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Erutan_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErutanServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erutan.Erutan/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErutanServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Erutan_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ErutanServer).Stream(&erutanStreamServer{stream})
}

type Erutan_StreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type erutanStreamServer struct {
	grpc.ServerStream
}

func (x *erutanStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *erutanStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Erutan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erutan.Erutan",
	HandlerType: (*ErutanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Erutan_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Erutan_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Erutan_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "realtime.proto",
}
