{
 "title": "Erutan",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} - alloc_bytes" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}} cpu_seconds_total"
    }
   ]
  },
  {
   "title": "Packet network updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(network_action_ignore[5m])",
     "legendFormat": "{{job}} - ignore"
    },
    {
     "expr": "rate(network_action_update[5m])",
     "legendFormat": "{{job}} - update"
    },
    {
     "expr": "rate(network_action_destroy[5m])",
     "legendFormat": "{{job}} - destroy"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_sent_total[5m])",
     "legendFormat": "{{job}} - server_msg_sent_total"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_established_total[5m])",
     "legendFormat": "{{job}} - Client connections"
    }
   ]
  }
 ]
}