// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/erutan.proto

package erutan

import (
	context "context"
	fmt "fmt"
	protometry "github.com/The-Tensox/protometry"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Component_BehaviourTypeComponent_Tag int32

const (
	Component_BehaviourTypeComponent_ANY        Component_BehaviourTypeComponent_Tag = 0
	Component_BehaviourTypeComponent_ANIMAL     Component_BehaviourTypeComponent_Tag = 1
	Component_BehaviourTypeComponent_VEGETATION Component_BehaviourTypeComponent_Tag = 2
)

var Component_BehaviourTypeComponent_Tag_name = map[int32]string{
	0: "ANY",
	1: "ANIMAL",
	2: "VEGETATION",
}

var Component_BehaviourTypeComponent_Tag_value = map[string]int32{
	"ANY":        0,
	"ANIMAL":     1,
	"VEGETATION": 2,
}

func (x Component_BehaviourTypeComponent_Tag) String() string {
	return proto.EnumName(Component_BehaviourTypeComponent_Tag_name, int32(x))
}

func (Component_BehaviourTypeComponent_Tag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 5, 0}
}

type Component_NetworkBehaviourComponent_Tag int32

const (
	Component_NetworkBehaviourComponent_ALL   Component_NetworkBehaviourComponent_Tag = 0
	Component_NetworkBehaviourComponent_DEBUG Component_NetworkBehaviourComponent_Tag = 1
)

var Component_NetworkBehaviourComponent_Tag_name = map[int32]string{
	0: "ALL",
	1: "DEBUG",
}

var Component_NetworkBehaviourComponent_Tag_value = map[string]int32{
	"ALL":   0,
	"DEBUG": 1,
}

func (x Component_NetworkBehaviourComponent_Tag) String() string {
	return proto.EnumName(Component_NetworkBehaviourComponent_Tag_name, int32(x))
}

func (Component_NetworkBehaviourComponent_Tag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 7, 0}
}

type Metadata struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// Mesh is used for rendering meshes
type Mesh struct {
	Vertices             []*protometry.VectorN `protobuf:"bytes,2,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Tris                 []int32               `protobuf:"varint,3,rep,packed,name=tris,proto3" json:"tris,omitempty"`
	Normals              []*protometry.VectorN `protobuf:"bytes,4,rep,name=normals,proto3" json:"normals,omitempty"`
	Uvs                  []*protometry.VectorN `protobuf:"bytes,5,rep,name=uvs,proto3" json:"uvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Mesh) Reset()         { *m = Mesh{} }
func (m *Mesh) String() string { return proto.CompactTextString(m) }
func (*Mesh) ProtoMessage()    {}
func (*Mesh) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{1}
}

func (m *Mesh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh.Unmarshal(m, b)
}
func (m *Mesh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh.Marshal(b, m, deterministic)
}
func (m *Mesh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh.Merge(m, src)
}
func (m *Mesh) XXX_Size() int {
	return xxx_messageInfo_Mesh.Size(m)
}
func (m *Mesh) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh proto.InternalMessageInfo

func (m *Mesh) GetVertices() []*protometry.VectorN {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *Mesh) GetTris() []int32 {
	if m != nil {
		return m.Tris
	}
	return nil
}

func (m *Mesh) GetNormals() []*protometry.VectorN {
	if m != nil {
		return m.Normals
	}
	return nil
}

func (m *Mesh) GetUvs() []*protometry.VectorN {
	if m != nil {
		return m.Uvs
	}
	return nil
}

// Data-oriented design : Entity Component System (ECS)
type Component struct {
	// Types that are valid to be assigned to Type:
	//	*Component_Space
	//	*Component_Health
	//	*Component_Speed
	//	*Component_Render
	//	*Component_BehaviourType
	//	*Component_Physics
	//	*Component_NetworkBehaviour
	Type                 isComponent_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

type isComponent_Type interface {
	isComponent_Type()
}

type Component_Space struct {
	Space *Component_SpaceComponent `protobuf:"bytes,1,opt,name=space,proto3,oneof"`
}

type Component_Health struct {
	Health *Component_HealthComponent `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

type Component_Speed struct {
	Speed *Component_SpeedComponent `protobuf:"bytes,3,opt,name=speed,proto3,oneof"`
}

type Component_Render struct {
	Render *Component_RenderComponent `protobuf:"bytes,4,opt,name=render,proto3,oneof"`
}

type Component_BehaviourType struct {
	BehaviourType *Component_BehaviourTypeComponent `protobuf:"bytes,5,opt,name=behaviour_type,json=behaviourType,proto3,oneof"`
}

type Component_Physics struct {
	Physics *Component_PhysicsComponent `protobuf:"bytes,6,opt,name=physics,proto3,oneof"`
}

type Component_NetworkBehaviour struct {
	NetworkBehaviour *Component_NetworkBehaviourComponent `protobuf:"bytes,7,opt,name=network_behaviour,json=networkBehaviour,proto3,oneof"`
}

func (*Component_Space) isComponent_Type() {}

func (*Component_Health) isComponent_Type() {}

func (*Component_Speed) isComponent_Type() {}

func (*Component_Render) isComponent_Type() {}

func (*Component_BehaviourType) isComponent_Type() {}

func (*Component_Physics) isComponent_Type() {}

func (*Component_NetworkBehaviour) isComponent_Type() {}

func (m *Component) GetType() isComponent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Component) GetSpace() *Component_SpaceComponent {
	if x, ok := m.GetType().(*Component_Space); ok {
		return x.Space
	}
	return nil
}

func (m *Component) GetHealth() *Component_HealthComponent {
	if x, ok := m.GetType().(*Component_Health); ok {
		return x.Health
	}
	return nil
}

func (m *Component) GetSpeed() *Component_SpeedComponent {
	if x, ok := m.GetType().(*Component_Speed); ok {
		return x.Speed
	}
	return nil
}

func (m *Component) GetRender() *Component_RenderComponent {
	if x, ok := m.GetType().(*Component_Render); ok {
		return x.Render
	}
	return nil
}

func (m *Component) GetBehaviourType() *Component_BehaviourTypeComponent {
	if x, ok := m.GetType().(*Component_BehaviourType); ok {
		return x.BehaviourType
	}
	return nil
}

func (m *Component) GetPhysics() *Component_PhysicsComponent {
	if x, ok := m.GetType().(*Component_Physics); ok {
		return x.Physics
	}
	return nil
}

func (m *Component) GetNetworkBehaviour() *Component_NetworkBehaviourComponent {
	if x, ok := m.GetType().(*Component_NetworkBehaviour); ok {
		return x.NetworkBehaviour
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Component) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Component_Space)(nil),
		(*Component_Health)(nil),
		(*Component_Speed)(nil),
		(*Component_Render)(nil),
		(*Component_BehaviourType)(nil),
		(*Component_Physics)(nil),
		(*Component_NetworkBehaviour)(nil),
	}
}

type Component_SpaceComponent struct {
	Position             *protometry.VectorN     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *protometry.QuaternionN `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale                *protometry.VectorN     `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`
	Mesh                 *Mesh                   `protobuf:"bytes,4,opt,name=mesh,proto3" json:"mesh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Component_SpaceComponent) Reset()         { *m = Component_SpaceComponent{} }
func (m *Component_SpaceComponent) String() string { return proto.CompactTextString(m) }
func (*Component_SpaceComponent) ProtoMessage()    {}
func (*Component_SpaceComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 0}
}

func (m *Component_SpaceComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_SpaceComponent.Unmarshal(m, b)
}
func (m *Component_SpaceComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_SpaceComponent.Marshal(b, m, deterministic)
}
func (m *Component_SpaceComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_SpaceComponent.Merge(m, src)
}
func (m *Component_SpaceComponent) XXX_Size() int {
	return xxx_messageInfo_Component_SpaceComponent.Size(m)
}
func (m *Component_SpaceComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_SpaceComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_SpaceComponent proto.InternalMessageInfo

func (m *Component_SpaceComponent) GetPosition() *protometry.VectorN {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Component_SpaceComponent) GetRotation() *protometry.QuaternionN {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Component_SpaceComponent) GetScale() *protometry.VectorN {
	if m != nil {
		return m.Scale
	}
	return nil
}

func (m *Component_SpaceComponent) GetMesh() *Mesh {
	if m != nil {
		return m.Mesh
	}
	return nil
}

type Component_HealthComponent struct {
	Life                 float64  `protobuf:"fixed64,1,opt,name=life,proto3" json:"life,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_HealthComponent) Reset()         { *m = Component_HealthComponent{} }
func (m *Component_HealthComponent) String() string { return proto.CompactTextString(m) }
func (*Component_HealthComponent) ProtoMessage()    {}
func (*Component_HealthComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 1}
}

func (m *Component_HealthComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_HealthComponent.Unmarshal(m, b)
}
func (m *Component_HealthComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_HealthComponent.Marshal(b, m, deterministic)
}
func (m *Component_HealthComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_HealthComponent.Merge(m, src)
}
func (m *Component_HealthComponent) XXX_Size() int {
	return xxx_messageInfo_Component_HealthComponent.Size(m)
}
func (m *Component_HealthComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_HealthComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_HealthComponent proto.InternalMessageInfo

func (m *Component_HealthComponent) GetLife() float64 {
	if m != nil {
		return m.Life
	}
	return 0
}

type Component_SpeedComponent struct {
	MoveSpeed            float64  `protobuf:"fixed64,1,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_SpeedComponent) Reset()         { *m = Component_SpeedComponent{} }
func (m *Component_SpeedComponent) String() string { return proto.CompactTextString(m) }
func (*Component_SpeedComponent) ProtoMessage()    {}
func (*Component_SpeedComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 2}
}

func (m *Component_SpeedComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_SpeedComponent.Unmarshal(m, b)
}
func (m *Component_SpeedComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_SpeedComponent.Marshal(b, m, deterministic)
}
func (m *Component_SpeedComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_SpeedComponent.Merge(m, src)
}
func (m *Component_SpeedComponent) XXX_Size() int {
	return xxx_messageInfo_Component_SpeedComponent.Size(m)
}
func (m *Component_SpeedComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_SpeedComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_SpeedComponent proto.InternalMessageInfo

func (m *Component_SpeedComponent) GetMoveSpeed() float64 {
	if m != nil {
		return m.MoveSpeed
	}
	return 0
}

type Component_TargetComponent struct {
	Target               *protometry.VectorN `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Component_TargetComponent) Reset()         { *m = Component_TargetComponent{} }
func (m *Component_TargetComponent) String() string { return proto.CompactTextString(m) }
func (*Component_TargetComponent) ProtoMessage()    {}
func (*Component_TargetComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 3}
}

func (m *Component_TargetComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_TargetComponent.Unmarshal(m, b)
}
func (m *Component_TargetComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_TargetComponent.Marshal(b, m, deterministic)
}
func (m *Component_TargetComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_TargetComponent.Merge(m, src)
}
func (m *Component_TargetComponent) XXX_Size() int {
	return xxx_messageInfo_Component_TargetComponent.Size(m)
}
func (m *Component_TargetComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_TargetComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_TargetComponent proto.InternalMessageInfo

func (m *Component_TargetComponent) GetTarget() *protometry.VectorN {
	if m != nil {
		return m.Target
	}
	return nil
}

type Component_RenderComponent struct {
	Red                  float32  `protobuf:"fixed32,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                float32  `protobuf:"fixed32,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 float32  `protobuf:"fixed32,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Alpha                float32  `protobuf:"fixed32,4,opt,name=alpha,proto3" json:"alpha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_RenderComponent) Reset()         { *m = Component_RenderComponent{} }
func (m *Component_RenderComponent) String() string { return proto.CompactTextString(m) }
func (*Component_RenderComponent) ProtoMessage()    {}
func (*Component_RenderComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 4}
}

func (m *Component_RenderComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_RenderComponent.Unmarshal(m, b)
}
func (m *Component_RenderComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_RenderComponent.Marshal(b, m, deterministic)
}
func (m *Component_RenderComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_RenderComponent.Merge(m, src)
}
func (m *Component_RenderComponent) XXX_Size() int {
	return xxx_messageInfo_Component_RenderComponent.Size(m)
}
func (m *Component_RenderComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_RenderComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_RenderComponent proto.InternalMessageInfo

func (m *Component_RenderComponent) GetRed() float32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Component_RenderComponent) GetGreen() float32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Component_RenderComponent) GetBlue() float32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

func (m *Component_RenderComponent) GetAlpha() float32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

// Acts as a sort of tag
type Component_BehaviourTypeComponent struct {
	Tag                  Component_BehaviourTypeComponent_Tag `protobuf:"varint,1,opt,name=tag,proto3,enum=erutan.Component_BehaviourTypeComponent_Tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Component_BehaviourTypeComponent) Reset()         { *m = Component_BehaviourTypeComponent{} }
func (m *Component_BehaviourTypeComponent) String() string { return proto.CompactTextString(m) }
func (*Component_BehaviourTypeComponent) ProtoMessage()    {}
func (*Component_BehaviourTypeComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 5}
}

func (m *Component_BehaviourTypeComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Unmarshal(m, b)
}
func (m *Component_BehaviourTypeComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Marshal(b, m, deterministic)
}
func (m *Component_BehaviourTypeComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_BehaviourTypeComponent.Merge(m, src)
}
func (m *Component_BehaviourTypeComponent) XXX_Size() int {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Size(m)
}
func (m *Component_BehaviourTypeComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_BehaviourTypeComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_BehaviourTypeComponent proto.InternalMessageInfo

func (m *Component_BehaviourTypeComponent) GetTag() Component_BehaviourTypeComponent_Tag {
	if m != nil {
		return m.Tag
	}
	return Component_BehaviourTypeComponent_ANY
}

type Component_PhysicsComponent struct {
	UseGravity           bool     `protobuf:"varint,1,opt,name=use_gravity,json=useGravity,proto3" json:"use_gravity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_PhysicsComponent) Reset()         { *m = Component_PhysicsComponent{} }
func (m *Component_PhysicsComponent) String() string { return proto.CompactTextString(m) }
func (*Component_PhysicsComponent) ProtoMessage()    {}
func (*Component_PhysicsComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 6}
}

func (m *Component_PhysicsComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_PhysicsComponent.Unmarshal(m, b)
}
func (m *Component_PhysicsComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_PhysicsComponent.Marshal(b, m, deterministic)
}
func (m *Component_PhysicsComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_PhysicsComponent.Merge(m, src)
}
func (m *Component_PhysicsComponent) XXX_Size() int {
	return xxx_messageInfo_Component_PhysicsComponent.Size(m)
}
func (m *Component_PhysicsComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_PhysicsComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_PhysicsComponent proto.InternalMessageInfo

func (m *Component_PhysicsComponent) GetUseGravity() bool {
	if m != nil {
		return m.UseGravity
	}
	return false
}

// Some information about how this object should be synchronized
type Component_NetworkBehaviourComponent struct {
	Tag                  Component_NetworkBehaviourComponent_Tag `protobuf:"varint,1,opt,name=tag,proto3,enum=erutan.Component_NetworkBehaviourComponent_Tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *Component_NetworkBehaviourComponent) Reset()         { *m = Component_NetworkBehaviourComponent{} }
func (m *Component_NetworkBehaviourComponent) String() string { return proto.CompactTextString(m) }
func (*Component_NetworkBehaviourComponent) ProtoMessage()    {}
func (*Component_NetworkBehaviourComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2, 7}
}

func (m *Component_NetworkBehaviourComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_NetworkBehaviourComponent.Unmarshal(m, b)
}
func (m *Component_NetworkBehaviourComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_NetworkBehaviourComponent.Marshal(b, m, deterministic)
}
func (m *Component_NetworkBehaviourComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_NetworkBehaviourComponent.Merge(m, src)
}
func (m *Component_NetworkBehaviourComponent) XXX_Size() int {
	return xxx_messageInfo_Component_NetworkBehaviourComponent.Size(m)
}
func (m *Component_NetworkBehaviourComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_NetworkBehaviourComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_NetworkBehaviourComponent proto.InternalMessageInfo

func (m *Component_NetworkBehaviourComponent) GetTag() Component_NetworkBehaviourComponent_Tag {
	if m != nil {
		return m.Tag
	}
	return Component_NetworkBehaviourComponent_ALL
}

type Packet struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// TODO: entity -> object ? or maybe not
	//
	// Types that are valid to be assigned to Type:
	//	*Packet_CreateEntity
	//	*Packet_UpdateEntity
	//	*Packet_UpdatePosition
	//	*Packet_UpdateRotation
	//	*Packet_DestroyEntity
	//	*Packet_UpdateAnimal
	//	*Packet_UpdateParameters
	Type                 isPacket_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isPacket_Type interface {
	isPacket_Type()
}

type Packet_CreateEntity struct {
	CreateEntity *Packet_CreateEntityPacket `protobuf:"bytes,2,opt,name=create_entity,json=createEntity,proto3,oneof"`
}

type Packet_UpdateEntity struct {
	UpdateEntity *Packet_UpdateEntityPacket `protobuf:"bytes,3,opt,name=update_entity,json=updateEntity,proto3,oneof"`
}

type Packet_UpdatePosition struct {
	UpdatePosition *Packet_UpdatePositionPacket `protobuf:"bytes,4,opt,name=update_position,json=updatePosition,proto3,oneof"`
}

type Packet_UpdateRotation struct {
	UpdateRotation *Packet_UpdateRotationPacket `protobuf:"bytes,5,opt,name=update_rotation,json=updateRotation,proto3,oneof"`
}

type Packet_DestroyEntity struct {
	DestroyEntity *Packet_DestroyEntityPacket `protobuf:"bytes,6,opt,name=destroy_entity,json=destroyEntity,proto3,oneof"`
}

type Packet_UpdateAnimal struct {
	UpdateAnimal *Packet_UpdateAnimalPacket `protobuf:"bytes,7,opt,name=update_animal,json=updateAnimal,proto3,oneof"`
}

type Packet_UpdateParameters struct {
	UpdateParameters *Packet_UpdateParametersPacket `protobuf:"bytes,8,opt,name=update_parameters,json=updateParameters,proto3,oneof"`
}

func (*Packet_CreateEntity) isPacket_Type() {}

func (*Packet_UpdateEntity) isPacket_Type() {}

func (*Packet_UpdatePosition) isPacket_Type() {}

func (*Packet_UpdateRotation) isPacket_Type() {}

func (*Packet_DestroyEntity) isPacket_Type() {}

func (*Packet_UpdateAnimal) isPacket_Type() {}

func (*Packet_UpdateParameters) isPacket_Type() {}

func (m *Packet) GetType() isPacket_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Packet) GetCreateEntity() *Packet_CreateEntityPacket {
	if x, ok := m.GetType().(*Packet_CreateEntity); ok {
		return x.CreateEntity
	}
	return nil
}

func (m *Packet) GetUpdateEntity() *Packet_UpdateEntityPacket {
	if x, ok := m.GetType().(*Packet_UpdateEntity); ok {
		return x.UpdateEntity
	}
	return nil
}

func (m *Packet) GetUpdatePosition() *Packet_UpdatePositionPacket {
	if x, ok := m.GetType().(*Packet_UpdatePosition); ok {
		return x.UpdatePosition
	}
	return nil
}

func (m *Packet) GetUpdateRotation() *Packet_UpdateRotationPacket {
	if x, ok := m.GetType().(*Packet_UpdateRotation); ok {
		return x.UpdateRotation
	}
	return nil
}

func (m *Packet) GetDestroyEntity() *Packet_DestroyEntityPacket {
	if x, ok := m.GetType().(*Packet_DestroyEntity); ok {
		return x.DestroyEntity
	}
	return nil
}

func (m *Packet) GetUpdateAnimal() *Packet_UpdateAnimalPacket {
	if x, ok := m.GetType().(*Packet_UpdateAnimal); ok {
		return x.UpdateAnimal
	}
	return nil
}

func (m *Packet) GetUpdateParameters() *Packet_UpdateParametersPacket {
	if x, ok := m.GetType().(*Packet_UpdateParameters); ok {
		return x.UpdateParameters
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_CreateEntity)(nil),
		(*Packet_UpdateEntity)(nil),
		(*Packet_UpdatePosition)(nil),
		(*Packet_UpdateRotation)(nil),
		(*Packet_DestroyEntity)(nil),
		(*Packet_UpdateAnimal)(nil),
		(*Packet_UpdateParameters)(nil),
	}
}

type Packet_CreateEntityPacket struct {
	EntityId             uint64       `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components           []*Component `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Packet_CreateEntityPacket) Reset()         { *m = Packet_CreateEntityPacket{} }
func (m *Packet_CreateEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_CreateEntityPacket) ProtoMessage()    {}
func (*Packet_CreateEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 0}
}

func (m *Packet_CreateEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_CreateEntityPacket.Unmarshal(m, b)
}
func (m *Packet_CreateEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_CreateEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_CreateEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_CreateEntityPacket.Merge(m, src)
}
func (m *Packet_CreateEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_CreateEntityPacket.Size(m)
}
func (m *Packet_CreateEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_CreateEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_CreateEntityPacket proto.InternalMessageInfo

func (m *Packet_CreateEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_CreateEntityPacket) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

type Packet_UpdateEntityPacket struct {
	EntityId             uint64       `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components           []*Component `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Packet_UpdateEntityPacket) Reset()         { *m = Packet_UpdateEntityPacket{} }
func (m *Packet_UpdateEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateEntityPacket) ProtoMessage()    {}
func (*Packet_UpdateEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 1}
}

func (m *Packet_UpdateEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateEntityPacket.Merge(m, src)
}
func (m *Packet_UpdateEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Size(m)
}
func (m *Packet_UpdateEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateEntityPacket proto.InternalMessageInfo

func (m *Packet_UpdateEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateEntityPacket) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

type Packet_UpdatePositionPacket struct {
	EntityId             uint64              `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Position             *protometry.VectorN `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Packet_UpdatePositionPacket) Reset()         { *m = Packet_UpdatePositionPacket{} }
func (m *Packet_UpdatePositionPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdatePositionPacket) ProtoMessage()    {}
func (*Packet_UpdatePositionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 2}
}

func (m *Packet_UpdatePositionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Unmarshal(m, b)
}
func (m *Packet_UpdatePositionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdatePositionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdatePositionPacket.Merge(m, src)
}
func (m *Packet_UpdatePositionPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Size(m)
}
func (m *Packet_UpdatePositionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdatePositionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdatePositionPacket proto.InternalMessageInfo

func (m *Packet_UpdatePositionPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdatePositionPacket) GetPosition() *protometry.VectorN {
	if m != nil {
		return m.Position
	}
	return nil
}

type Packet_UpdateRotationPacket struct {
	EntityId             uint64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Rotation             *protometry.QuaternionN `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Packet_UpdateRotationPacket) Reset()         { *m = Packet_UpdateRotationPacket{} }
func (m *Packet_UpdateRotationPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateRotationPacket) ProtoMessage()    {}
func (*Packet_UpdateRotationPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 3}
}

func (m *Packet_UpdateRotationPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateRotationPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateRotationPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateRotationPacket.Merge(m, src)
}
func (m *Packet_UpdateRotationPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Size(m)
}
func (m *Packet_UpdateRotationPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateRotationPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateRotationPacket proto.InternalMessageInfo

func (m *Packet_UpdateRotationPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateRotationPacket) GetRotation() *protometry.QuaternionN {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Packet_DestroyEntityPacket struct {
	EntityId             uint64   `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_DestroyEntityPacket) Reset()         { *m = Packet_DestroyEntityPacket{} }
func (m *Packet_DestroyEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_DestroyEntityPacket) ProtoMessage()    {}
func (*Packet_DestroyEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 4}
}

func (m *Packet_DestroyEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Unmarshal(m, b)
}
func (m *Packet_DestroyEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_DestroyEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_DestroyEntityPacket.Merge(m, src)
}
func (m *Packet_DestroyEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Size(m)
}
func (m *Packet_DestroyEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_DestroyEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_DestroyEntityPacket proto.InternalMessageInfo

func (m *Packet_DestroyEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type Packet_UpdateAnimalPacket struct {
	EntityId             uint64   `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Life                 float64  `protobuf:"fixed64,2,opt,name=life,proto3" json:"life,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_UpdateAnimalPacket) Reset()         { *m = Packet_UpdateAnimalPacket{} }
func (m *Packet_UpdateAnimalPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateAnimalPacket) ProtoMessage()    {}
func (*Packet_UpdateAnimalPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 5}
}

func (m *Packet_UpdateAnimalPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateAnimalPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateAnimalPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateAnimalPacket.Merge(m, src)
}
func (m *Packet_UpdateAnimalPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Size(m)
}
func (m *Packet_UpdateAnimalPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateAnimalPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateAnimalPacket proto.InternalMessageInfo

func (m *Packet_UpdateAnimalPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateAnimalPacket) GetLife() float64 {
	if m != nil {
		return m.Life
	}
	return 0
}

type Packet_UpdateParametersPacket struct {
	Parameters           []*Packet_UpdateParametersPacket_Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Packet_UpdateParametersPacket) Reset()         { *m = Packet_UpdateParametersPacket{} }
func (m *Packet_UpdateParametersPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateParametersPacket) ProtoMessage()    {}
func (*Packet_UpdateParametersPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 6}
}

func (m *Packet_UpdateParametersPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateParametersPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateParametersPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateParametersPacket.Merge(m, src)
}
func (m *Packet_UpdateParametersPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Size(m)
}
func (m *Packet_UpdateParametersPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateParametersPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateParametersPacket proto.InternalMessageInfo

func (m *Packet_UpdateParametersPacket) GetParameters() []*Packet_UpdateParametersPacket_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Packet_UpdateParametersPacket_Parameter struct {
	// Types that are valid to be assigned to Type:
	//	*Packet_UpdateParametersPacket_Parameter_TimeScale
	//	*Packet_UpdateParametersPacket_Parameter_Debug
	Type                 isPacket_UpdateParametersPacket_Parameter_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Packet_UpdateParametersPacket_Parameter) Reset() {
	*m = Packet_UpdateParametersPacket_Parameter{}
}
func (m *Packet_UpdateParametersPacket_Parameter) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateParametersPacket_Parameter) ProtoMessage()    {}
func (*Packet_UpdateParametersPacket_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3, 6, 0}
}

func (m *Packet_UpdateParametersPacket_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Unmarshal(m, b)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Merge(m, src)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Size(m)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateParametersPacket_Parameter proto.InternalMessageInfo

type isPacket_UpdateParametersPacket_Parameter_Type interface {
	isPacket_UpdateParametersPacket_Parameter_Type()
}

type Packet_UpdateParametersPacket_Parameter_TimeScale struct {
	TimeScale float64 `protobuf:"fixed64,1,opt,name=time_scale,json=timeScale,proto3,oneof"`
}

type Packet_UpdateParametersPacket_Parameter_Debug struct {
	Debug bool `protobuf:"varint,2,opt,name=debug,proto3,oneof"`
}

func (*Packet_UpdateParametersPacket_Parameter_TimeScale) isPacket_UpdateParametersPacket_Parameter_Type() {
}

func (*Packet_UpdateParametersPacket_Parameter_Debug) isPacket_UpdateParametersPacket_Parameter_Type() {
}

func (m *Packet_UpdateParametersPacket_Parameter) GetType() isPacket_UpdateParametersPacket_Parameter_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Packet_UpdateParametersPacket_Parameter) GetTimeScale() float64 {
	if x, ok := m.GetType().(*Packet_UpdateParametersPacket_Parameter_TimeScale); ok {
		return x.TimeScale
	}
	return 0
}

func (m *Packet_UpdateParametersPacket_Parameter) GetDebug() bool {
	if x, ok := m.GetType().(*Packet_UpdateParametersPacket_Parameter_Debug); ok {
		return x.Debug
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet_UpdateParametersPacket_Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_UpdateParametersPacket_Parameter_TimeScale)(nil),
		(*Packet_UpdateParametersPacket_Parameter_Debug)(nil),
	}
}

func init() {
	proto.RegisterEnum("erutan.Component_BehaviourTypeComponent_Tag", Component_BehaviourTypeComponent_Tag_name, Component_BehaviourTypeComponent_Tag_value)
	proto.RegisterEnum("erutan.Component_NetworkBehaviourComponent_Tag", Component_NetworkBehaviourComponent_Tag_name, Component_NetworkBehaviourComponent_Tag_value)
	proto.RegisterType((*Metadata)(nil), "erutan.Metadata")
	proto.RegisterType((*Mesh)(nil), "erutan.Mesh")
	proto.RegisterType((*Component)(nil), "erutan.Component")
	proto.RegisterType((*Component_SpaceComponent)(nil), "erutan.Component.SpaceComponent")
	proto.RegisterType((*Component_HealthComponent)(nil), "erutan.Component.HealthComponent")
	proto.RegisterType((*Component_SpeedComponent)(nil), "erutan.Component.SpeedComponent")
	proto.RegisterType((*Component_TargetComponent)(nil), "erutan.Component.TargetComponent")
	proto.RegisterType((*Component_RenderComponent)(nil), "erutan.Component.RenderComponent")
	proto.RegisterType((*Component_BehaviourTypeComponent)(nil), "erutan.Component.BehaviourTypeComponent")
	proto.RegisterType((*Component_PhysicsComponent)(nil), "erutan.Component.PhysicsComponent")
	proto.RegisterType((*Component_NetworkBehaviourComponent)(nil), "erutan.Component.NetworkBehaviourComponent")
	proto.RegisterType((*Packet)(nil), "erutan.Packet")
	proto.RegisterType((*Packet_CreateEntityPacket)(nil), "erutan.Packet.CreateEntityPacket")
	proto.RegisterType((*Packet_UpdateEntityPacket)(nil), "erutan.Packet.UpdateEntityPacket")
	proto.RegisterType((*Packet_UpdatePositionPacket)(nil), "erutan.Packet.UpdatePositionPacket")
	proto.RegisterType((*Packet_UpdateRotationPacket)(nil), "erutan.Packet.UpdateRotationPacket")
	proto.RegisterType((*Packet_DestroyEntityPacket)(nil), "erutan.Packet.DestroyEntityPacket")
	proto.RegisterType((*Packet_UpdateAnimalPacket)(nil), "erutan.Packet.UpdateAnimalPacket")
	proto.RegisterType((*Packet_UpdateParametersPacket)(nil), "erutan.Packet.UpdateParametersPacket")
	proto.RegisterType((*Packet_UpdateParametersPacket_Parameter)(nil), "erutan.Packet.UpdateParametersPacket.Parameter")
}

func init() {
	proto.RegisterFile("protobuf/erutan.proto", fileDescriptor_647af75c89a25519)
}

var fileDescriptor_647af75c89a25519 = []byte{
	// 1104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xf5, 0x67, 0x69, 0x1c, 0xcb, 0xf2, 0x26, 0x75, 0x19, 0xb6, 0x85, 0x1d, 0x15, 0x46,
	0xdd, 0x26, 0xa1, 0x5a, 0xfb, 0x62, 0xa0, 0x80, 0x01, 0x39, 0x16, 0x6c, 0xa3, 0xb6, 0xe2, 0xd0,
	0x4a, 0x80, 0xe6, 0x22, 0xac, 0xc8, 0x89, 0x44, 0x44, 0x24, 0xd5, 0xe5, 0x52, 0xad, 0xee, 0x7d,
	0x91, 0x5e, 0x7b, 0xea, 0xad, 0x0f, 0xd0, 0xb7, 0xe9, 0x53, 0x14, 0xdc, 0x25, 0x29, 0x8a, 0xa2,
	0x05, 0xb7, 0x40, 0x4f, 0xe4, 0xce, 0x7e, 0xf3, 0xcd, 0xce, 0xcc, 0xb7, 0x3f, 0xf0, 0xc9, 0x94,
	0x79, 0xdc, 0x1b, 0x06, 0x1f, 0xda, 0xc8, 0x02, 0x4e, 0x5d, 0x5d, 0x8c, 0x49, 0x55, 0x8e, 0xb4,
	0xbd, 0x91, 0xe7, 0x8d, 0x26, 0xd8, 0x4e, 0x50, 0xdc, 0x76, 0xd0, 0xe7, 0xd4, 0x99, 0x4a, 0xa0,
	0xf6, 0x2c, 0x99, 0x11, 0x3f, 0x0e, 0x72, 0x36, 0x6f, 0xcf, 0xd0, 0xe4, 0x1e, 0x8b, 0xb8, 0xb4,
	0x83, 0x3c, 0xc8, 0x4f, 0x01, 0xe5, 0xc8, 0x5c, 0xdb, 0x73, 0x23, 0x58, 0xeb, 0x1c, 0x6a, 0x37,
	0xc8, 0xa9, 0x45, 0x39, 0x25, 0x27, 0x50, 0x4f, 0x02, 0xa9, 0xca, 0xbe, 0x72, 0xb8, 0x79, 0xa4,
	0xe9, 0x72, 0x29, 0x7a, 0xcc, 0xa6, 0xf7, 0x63, 0x84, 0xb1, 0x00, 0xb7, 0x7e, 0x53, 0xa0, 0x7c,
	0x83, 0xfe, 0x98, 0xb4, 0xa1, 0x36, 0x43, 0xc6, 0x6d, 0x13, 0x7d, 0xb5, 0xb8, 0x5f, 0x3a, 0xdc,
	0x3c, 0x7a, 0xac, 0x2f, 0xe2, 0xeb, 0xef, 0xc4, 0x12, 0x7b, 0x46, 0x02, 0x22, 0x04, 0xca, 0x9c,
	0xd9, 0xbe, 0x5a, 0xda, 0x2f, 0x1d, 0x56, 0x0c, 0xf1, 0x4f, 0x5e, 0xc2, 0x86, 0xeb, 0x31, 0x87,
	0x4e, 0x7c, 0xb5, 0x7c, 0x3f, 0x47, 0x8c, 0x21, 0x07, 0x50, 0x0a, 0x66, 0xbe, 0x5a, 0xb9, 0x1f,
	0x1a, 0xce, 0xb7, 0xfe, 0xae, 0x43, 0xfd, 0x95, 0xe7, 0x4c, 0x3d, 0x17, 0x5d, 0x4e, 0x4e, 0xa0,
	0xe2, 0x4f, 0xa9, 0x89, 0x51, 0x9e, 0xfb, 0x7a, 0xd4, 0x88, 0x04, 0xa1, 0xdf, 0x85, 0xd3, 0xc9,
	0xf0, 0xb2, 0x60, 0x48, 0x07, 0xf2, 0x3d, 0x54, 0xc7, 0x48, 0x27, 0x7c, 0xac, 0x16, 0x85, 0xeb,
	0xb3, 0x55, 0xd7, 0x4b, 0x31, 0x9f, 0xf6, 0x8d, 0x5c, 0x64, 0x58, 0x44, 0x4b, 0x2d, 0xdd, 0x1f,
	0x16, 0xd1, 0xca, 0x84, 0x45, 0xb4, 0xc2, 0xb0, 0x0c, 0x5d, 0x0b, 0x99, 0x5a, 0xbe, 0x2f, 0xac,
	0x21, 0xe6, 0x97, 0xc2, 0x4a, 0x17, 0xf2, 0x06, 0x1a, 0x43, 0x1c, 0xd3, 0x99, 0xed, 0x05, 0x6c,
	0xc0, 0xe7, 0x53, 0x54, 0x2b, 0x82, 0xe4, 0x70, 0x95, 0xe4, 0x2c, 0xc6, 0xf5, 0xe7, 0xd3, 0xa5,
	0xf4, 0xb7, 0x86, 0xe9, 0x19, 0x72, 0x0a, 0x1b, 0xd3, 0xf1, 0xdc, 0xb7, 0x4d, 0x5f, 0xad, 0x0a,
	0xae, 0xd6, 0x2a, 0xd7, 0xad, 0x04, 0xa4, 0x59, 0x62, 0x27, 0xf2, 0x1e, 0x76, 0x5c, 0xe4, 0x3f,
	0x7b, 0xec, 0xe3, 0x20, 0x21, 0x56, 0x37, 0x04, 0xd3, 0xf3, 0x55, 0xa6, 0x9e, 0x84, 0x26, 0x8b,
	0x4b, 0x53, 0x36, 0xdd, 0xcc, 0xa4, 0xf6, 0x97, 0x02, 0x8d, 0xe5, 0xf6, 0x85, 0xc2, 0x9c, 0x7a,
	0xbe, 0xcd, 0x6d, 0xcf, 0x8d, 0x5a, 0x9e, 0x2f, 0xcc, 0x18, 0x44, 0x8e, 0xa1, 0xc6, 0x3c, 0x4e,
	0x85, 0x83, 0x6c, 0xf4, 0xa7, 0x69, 0x87, 0x37, 0xc9, 0x4e, 0xea, 0x19, 0x09, 0x90, 0x7c, 0x0d,
	0x15, 0xdf, 0xa4, 0x13, 0x8c, 0xda, 0x9b, 0x1b, 0x42, 0x22, 0xc8, 0x3e, 0x94, 0x1d, 0xf4, 0xc7,
	0x51, 0x37, 0x1f, 0xc5, 0x29, 0x87, 0xbb, 0xc8, 0x10, 0x33, 0xda, 0x01, 0x6c, 0x67, 0x84, 0x14,
	0xee, 0x96, 0x89, 0xfd, 0x41, 0x8a, 0x56, 0x31, 0xc4, 0xbf, 0xd6, 0x0e, 0x73, 0x4d, 0x6b, 0x86,
	0x7c, 0x01, 0xe0, 0x78, 0x33, 0x1c, 0x48, 0xa5, 0x49, 0x6c, 0x3d, 0xb4, 0x08, 0x9c, 0x76, 0x0a,
	0xdb, 0x7d, 0xca, 0x46, 0xc8, 0x17, 0x1e, 0xcf, 0xa1, 0xca, 0x85, 0x69, 0x5d, 0x6d, 0x22, 0x88,
	0x66, 0xc2, 0x76, 0x46, 0x69, 0xa4, 0x09, 0x25, 0x16, 0x85, 0x2a, 0x1a, 0xe1, 0x2f, 0x79, 0x02,
	0x95, 0x11, 0x43, 0x94, 0xb5, 0x2b, 0x1a, 0x72, 0x10, 0xae, 0x7f, 0x38, 0x09, 0x64, 0x79, 0x8a,
	0x86, 0xf8, 0x0f, 0x91, 0x74, 0x32, 0x1d, 0x53, 0x51, 0x89, 0xa2, 0x21, 0x07, 0xda, 0xaf, 0x0a,
	0xec, 0xe6, 0x4b, 0x91, 0x9c, 0x42, 0x89, 0xd3, 0x91, 0x08, 0xd6, 0x38, 0x7a, 0xf1, 0x50, 0x05,
	0xeb, 0x7d, 0x3a, 0x32, 0x42, 0xc7, 0xd6, 0x37, 0x50, 0xea, 0xd3, 0x11, 0xd9, 0x80, 0x52, 0xa7,
	0xf7, 0x63, 0xb3, 0x40, 0x00, 0xaa, 0x9d, 0xde, 0xd5, 0x4d, 0xe7, 0xba, 0xa9, 0x90, 0x06, 0xc0,
	0xbb, 0xee, 0x45, 0xb7, 0xdf, 0xe9, 0x5f, 0xbd, 0xee, 0x35, 0x8b, 0xda, 0x31, 0x34, 0xb3, 0x22,
	0x26, 0x7b, 0xb0, 0x19, 0xf8, 0x38, 0x18, 0x31, 0x3a, 0xb3, 0xf9, 0x5c, 0xac, 0xa3, 0x66, 0x40,
	0xe0, 0xe3, 0x85, 0xb4, 0x68, 0x73, 0x78, 0x7a, 0xaf, 0x5e, 0x49, 0x27, 0xbd, 0xfa, 0xf6, 0xbf,
	0x50, 0xfa, 0x22, 0x81, 0xa7, 0x8b, 0x04, 0xae, 0xaf, 0x9b, 0x05, 0x52, 0x87, 0xca, 0x79, 0xf7,
	0xec, 0xed, 0x45, 0x53, 0x39, 0xab, 0x42, 0x39, 0xdc, 0xde, 0xad, 0x3f, 0x00, 0xaa, 0xb7, 0xd4,
	0xfc, 0x88, 0x9c, 0xbc, 0x80, 0x9a, 0x13, 0x9d, 0xf0, 0x51, 0x77, 0x9b, 0x0b, 0xb1, 0x49, 0xbb,
	0x91, 0x20, 0xc8, 0x25, 0x6c, 0x99, 0x0c, 0x29, 0xc7, 0x01, 0xba, 0x3c, 0x4c, 0x2f, 0x73, 0xc8,
	0x49, 0x52, 0xfd, 0x95, 0xc0, 0x74, 0x05, 0x44, 0x9a, 0x2e, 0x0b, 0xc6, 0x23, 0x33, 0x65, 0x0d,
	0x99, 0x82, 0xa9, 0x95, 0x62, 0x2a, 0xe5, 0x32, 0xbd, 0x15, 0x98, 0x2c, 0x53, 0x90, 0xb2, 0x92,
	0x1e, 0x6c, 0x47, 0x4c, 0xc9, 0x16, 0x96, 0xbb, 0xe6, 0xcb, 0x5c, 0xae, 0xdb, 0x08, 0x94, 0xb0,
	0x35, 0x82, 0x25, 0x7b, 0x8a, 0x2f, 0xd9, 0xe1, 0x95, 0x35, 0x7c, 0x46, 0x04, 0xca, 0xf2, 0xc5,
	0x76, 0xf2, 0x03, 0x34, 0x2c, 0xf4, 0x39, 0xf3, 0xe6, 0x71, 0xaa, 0x99, 0x13, 0x31, 0xa2, 0x3b,
	0x97, 0xa0, 0x4c, 0xae, 0x5b, 0x56, 0xda, 0x9c, 0x2a, 0x1b, 0x75, 0x6d, 0x87, 0x4e, 0xa2, 0x33,
	0x31, 0xbf, 0x6c, 0x1d, 0x01, 0xc9, 0x96, 0x4d, 0x5a, 0x49, 0x1f, 0x76, 0xe2, 0xb2, 0x51, 0x46,
	0x1d, 0xe4, 0xc8, 0x7c, 0xb5, 0x26, 0xd8, 0x0e, 0xf2, 0x0b, 0x97, 0xc0, 0x12, 0xc6, 0x66, 0x90,
	0x99, 0xd1, 0x2c, 0x20, 0xab, 0xcd, 0x27, 0x9f, 0x41, 0x5d, 0xa6, 0x3e, 0xb0, 0xe5, 0x31, 0x50,
	0x36, 0x6a, 0xd2, 0x70, 0x65, 0x91, 0xef, 0x00, 0xcc, 0x58, 0xc5, 0xf1, 0xb3, 0x60, 0x67, 0x45,
	0xf9, 0x46, 0x0a, 0x14, 0x46, 0x59, 0x15, 0xc6, 0xff, 0x10, 0xe5, 0x49, 0x9e, 0x64, 0xd6, 0xc7,
	0x49, 0xdf, 0x24, 0xc5, 0x07, 0xdc, 0x24, 0xda, 0x38, 0x8e, 0xb2, 0x2c, 0xa4, 0xf5, 0x51, 0xfe,
	0xcb, 0xf5, 0xa3, 0x1d, 0xc1, 0xe3, 0x1c, 0x8d, 0xad, 0x0d, 0xa4, 0x75, 0xe3, 0x4a, 0xa7, 0xb5,
	0xb4, 0x7e, 0x6d, 0xf1, 0x2d, 0x54, 0x4c, 0xdd, 0x42, 0x7f, 0x2a, 0xb0, 0x9b, 0xaf, 0x22, 0xf2,
	0x1a, 0x20, 0x25, 0x40, 0x45, 0x34, 0xa6, 0xfd, 0x20, 0x01, 0xea, 0x89, 0xc1, 0x48, 0x51, 0x68,
	0xd7, 0x50, 0x4f, 0x26, 0xc8, 0x1e, 0x40, 0xf8, 0x0e, 0x1d, 0xc8, 0x7b, 0x57, 0x5c, 0x76, 0x97,
	0x05, 0xf9, 0x36, 0xbd, 0x13, 0x17, 0xed, 0x2e, 0x54, 0x2c, 0x1c, 0x06, 0x23, 0xb1, 0xdc, 0x5a,
	0xf8, 0xa0, 0x12, 0xc3, 0xf8, 0xa8, 0x8c, 0xbf, 0x47, 0x27, 0x50, 0xed, 0x8a, 0x35, 0x11, 0x1d,
	0xaa, 0x77, 0x9c, 0x21, 0x75, 0x48, 0x63, 0x79, 0x99, 0x5a, 0x66, 0xdc, 0x2a, 0x1c, 0x2a, 0xdf,
	0x2a, 0x67, 0x5f, 0xbd, 0xff, 0x7c, 0x64, 0xf3, 0x71, 0x30, 0xd4, 0x4d, 0xcf, 0x69, 0xf7, 0xc7,
	0xf8, 0xb2, 0x8f, 0xae, 0xef, 0xfd, 0x12, 0x3d, 0xee, 0x7f, 0x2f, 0x46, 0xc4, 0xc3, 0xaa, 0xe8,
	0xe0, 0xf1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21, 0xfa, 0xf8, 0x1c, 0xff, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ErutanClient is the client API for Erutan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ErutanClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error)
}

type erutanClient struct {
	cc grpc.ClientConnInterface
}

func NewErutanClient(cc grpc.ClientConnInterface) ErutanClient {
	return &erutanClient{cc}
}

func (c *erutanClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Erutan_serviceDesc.Streams[0], "/erutan.Erutan/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &erutanStreamClient{stream}
	return x, nil
}

type Erutan_StreamClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type erutanStreamClient struct {
	grpc.ClientStream
}

func (x *erutanStreamClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *erutanStreamClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ErutanServer is the server API for Erutan service.
type ErutanServer interface {
	Stream(Erutan_StreamServer) error
}

// UnimplementedErutanServer can be embedded to have forward compatible implementations.
type UnimplementedErutanServer struct {
}

func (*UnimplementedErutanServer) Stream(srv Erutan_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterErutanServer(s *grpc.Server, srv ErutanServer) {
	s.RegisterService(&_Erutan_serviceDesc, srv)
}

func _Erutan_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ErutanServer).Stream(&erutanStreamServer{stream})
}

type Erutan_StreamServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type erutanStreamServer struct {
	grpc.ServerStream
}

func (x *erutanStreamServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *erutanStreamServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Erutan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erutan.Erutan",
	HandlerType: (*ErutanServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Erutan_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/erutan.proto",
}
