// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/erutan.proto

package erutan

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	protometry "protobuf/protometry"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QuaternionN from public import protobuf/protometry/quaternionn.proto
type QuaternionN = protometry.QuaternionN

type Component_BehaviourTypeComponent_BehaviourType int32

const (
	Component_BehaviourTypeComponent_ANY        Component_BehaviourTypeComponent_BehaviourType = 0
	Component_BehaviourTypeComponent_ANIMAL     Component_BehaviourTypeComponent_BehaviourType = 1
	Component_BehaviourTypeComponent_VEGETATION Component_BehaviourTypeComponent_BehaviourType = 2
)

var Component_BehaviourTypeComponent_BehaviourType_name = map[int32]string{
	0: "ANY",
	1: "ANIMAL",
	2: "VEGETATION",
}

var Component_BehaviourTypeComponent_BehaviourType_value = map[string]int32{
	"ANY":        0,
	"ANIMAL":     1,
	"VEGETATION": 2,
}

func (x Component_BehaviourTypeComponent_BehaviourType) String() string {
	return proto.EnumName(Component_BehaviourTypeComponent_BehaviourType_name, int32(x))
}

func (Component_BehaviourTypeComponent_BehaviourType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 6, 0}
}

type Metadata struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// Shape is a ...
type Shape struct {
	Vertices             []*protometry.VectorN `protobuf:"bytes,2,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Tris                 []int32               `protobuf:"varint,3,rep,packed,name=tris,proto3" json:"tris,omitempty"`
	Normals              []*protometry.VectorN `protobuf:"bytes,4,rep,name=normals,proto3" json:"normals,omitempty"`
	Uvs                  []*protometry.VectorN `protobuf:"bytes,5,rep,name=uvs,proto3" json:"uvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Shape) Reset()         { *m = Shape{} }
func (m *Shape) String() string { return proto.CompactTextString(m) }
func (*Shape) ProtoMessage()    {}
func (*Shape) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{1}
}

func (m *Shape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shape.Unmarshal(m, b)
}
func (m *Shape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shape.Marshal(b, m, deterministic)
}
func (m *Shape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shape.Merge(m, src)
}
func (m *Shape) XXX_Size() int {
	return xxx_messageInfo_Shape.Size(m)
}
func (m *Shape) XXX_DiscardUnknown() {
	xxx_messageInfo_Shape.DiscardUnknown(m)
}

var xxx_messageInfo_Shape proto.InternalMessageInfo

func (m *Shape) GetVertices() []*protometry.VectorN {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *Shape) GetTris() []int32 {
	if m != nil {
		return m.Tris
	}
	return nil
}

func (m *Shape) GetNormals() []*protometry.VectorN {
	if m != nil {
		return m.Normals
	}
	return nil
}

func (m *Shape) GetUvs() []*protometry.VectorN {
	if m != nil {
		return m.Uvs
	}
	return nil
}

type Collider struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collider) Reset()         { *m = Collider{} }
func (m *Collider) String() string { return proto.CompactTextString(m) }
func (*Collider) ProtoMessage()    {}
func (*Collider) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{2}
}

func (m *Collider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collider.Unmarshal(m, b)
}
func (m *Collider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collider.Marshal(b, m, deterministic)
}
func (m *Collider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collider.Merge(m, src)
}
func (m *Collider) XXX_Size() int {
	return xxx_messageInfo_Collider.Size(m)
}
func (m *Collider) XXX_DiscardUnknown() {
	xxx_messageInfo_Collider.DiscardUnknown(m)
}

var xxx_messageInfo_Collider proto.InternalMessageInfo

// Ellipse represnets an ellpitical shape.
// Cx and Cy are the x and y coordinates of the center of the ellipse.
// Rx and Ry are the x and y radius of the ellipse.
type Ellipse struct {
	Cx                   float64  `protobuf:"fixed64,1,opt,name=cx,proto3" json:"cx,omitempty"`
	Cy                   float64  `protobuf:"fixed64,2,opt,name=cy,proto3" json:"cy,omitempty"`
	Rx                   float64  `protobuf:"fixed64,3,opt,name=rx,proto3" json:"rx,omitempty"`
	Ry                   float64  `protobuf:"fixed64,4,opt,name=ry,proto3" json:"ry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ellipse) Reset()         { *m = Ellipse{} }
func (m *Ellipse) String() string { return proto.CompactTextString(m) }
func (*Ellipse) ProtoMessage()    {}
func (*Ellipse) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{3}
}

func (m *Ellipse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ellipse.Unmarshal(m, b)
}
func (m *Ellipse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ellipse.Marshal(b, m, deterministic)
}
func (m *Ellipse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ellipse.Merge(m, src)
}
func (m *Ellipse) XXX_Size() int {
	return xxx_messageInfo_Ellipse.Size(m)
}
func (m *Ellipse) XXX_DiscardUnknown() {
	xxx_messageInfo_Ellipse.DiscardUnknown(m)
}

var xxx_messageInfo_Ellipse proto.InternalMessageInfo

func (m *Ellipse) GetCx() float64 {
	if m != nil {
		return m.Cx
	}
	return 0
}

func (m *Ellipse) GetCy() float64 {
	if m != nil {
		return m.Cy
	}
	return 0
}

func (m *Ellipse) GetRx() float64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *Ellipse) GetRy() float64 {
	if m != nil {
		return m.Ry
	}
	return 0
}

// Data-oriented design like
type Component struct {
	// Types that are valid to be assigned to Type:
	//	*Component_Space
	//	*Component_SpaceTime
	//	*Component_Health
	//	*Component_Speed
	//	*Component_Render
	//	*Component_BehaviourType
	//	*Component_Physics
	Type                 isComponent_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

type isComponent_Type interface {
	isComponent_Type()
}

type Component_Space struct {
	Space *Component_SpaceComponent `protobuf:"bytes,1,opt,name=space,proto3,oneof"`
}

type Component_SpaceTime struct {
	SpaceTime *Component_SpaceTimeComponent `protobuf:"bytes,2,opt,name=space_time,json=spaceTime,proto3,oneof"`
}

type Component_Health struct {
	Health *Component_HealthComponent `protobuf:"bytes,3,opt,name=health,proto3,oneof"`
}

type Component_Speed struct {
	Speed *Component_SpeedComponent `protobuf:"bytes,4,opt,name=speed,proto3,oneof"`
}

type Component_Render struct {
	Render *Component_RenderComponent `protobuf:"bytes,5,opt,name=render,proto3,oneof"`
}

type Component_BehaviourType struct {
	BehaviourType *Component_BehaviourTypeComponent `protobuf:"bytes,6,opt,name=behaviour_type,json=behaviourType,proto3,oneof"`
}

type Component_Physics struct {
	Physics *Component_PhysicsComponent `protobuf:"bytes,7,opt,name=physics,proto3,oneof"`
}

func (*Component_Space) isComponent_Type() {}

func (*Component_SpaceTime) isComponent_Type() {}

func (*Component_Health) isComponent_Type() {}

func (*Component_Speed) isComponent_Type() {}

func (*Component_Render) isComponent_Type() {}

func (*Component_BehaviourType) isComponent_Type() {}

func (*Component_Physics) isComponent_Type() {}

func (m *Component) GetType() isComponent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Component) GetSpace() *Component_SpaceComponent {
	if x, ok := m.GetType().(*Component_Space); ok {
		return x.Space
	}
	return nil
}

func (m *Component) GetSpaceTime() *Component_SpaceTimeComponent {
	if x, ok := m.GetType().(*Component_SpaceTime); ok {
		return x.SpaceTime
	}
	return nil
}

func (m *Component) GetHealth() *Component_HealthComponent {
	if x, ok := m.GetType().(*Component_Health); ok {
		return x.Health
	}
	return nil
}

func (m *Component) GetSpeed() *Component_SpeedComponent {
	if x, ok := m.GetType().(*Component_Speed); ok {
		return x.Speed
	}
	return nil
}

func (m *Component) GetRender() *Component_RenderComponent {
	if x, ok := m.GetType().(*Component_Render); ok {
		return x.Render
	}
	return nil
}

func (m *Component) GetBehaviourType() *Component_BehaviourTypeComponent {
	if x, ok := m.GetType().(*Component_BehaviourType); ok {
		return x.BehaviourType
	}
	return nil
}

func (m *Component) GetPhysics() *Component_PhysicsComponent {
	if x, ok := m.GetType().(*Component_Physics); ok {
		return x.Physics
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Component) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Component_Space)(nil),
		(*Component_SpaceTime)(nil),
		(*Component_Health)(nil),
		(*Component_Speed)(nil),
		(*Component_Render)(nil),
		(*Component_BehaviourType)(nil),
		(*Component_Physics)(nil),
	}
}

type Component_SpaceComponent struct {
	Position             *protometry.VectorN     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *protometry.QuaternionN `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale                *protometry.VectorN     `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`
	Shape                *Shape                  `protobuf:"bytes,4,opt,name=shape,proto3" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Component_SpaceComponent) Reset()         { *m = Component_SpaceComponent{} }
func (m *Component_SpaceComponent) String() string { return proto.CompactTextString(m) }
func (*Component_SpaceComponent) ProtoMessage()    {}
func (*Component_SpaceComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 0}
}

func (m *Component_SpaceComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_SpaceComponent.Unmarshal(m, b)
}
func (m *Component_SpaceComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_SpaceComponent.Marshal(b, m, deterministic)
}
func (m *Component_SpaceComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_SpaceComponent.Merge(m, src)
}
func (m *Component_SpaceComponent) XXX_Size() int {
	return xxx_messageInfo_Component_SpaceComponent.Size(m)
}
func (m *Component_SpaceComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_SpaceComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_SpaceComponent proto.InternalMessageInfo

func (m *Component_SpaceComponent) GetPosition() *protometry.VectorN {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Component_SpaceComponent) GetRotation() *protometry.QuaternionN {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Component_SpaceComponent) GetScale() *protometry.VectorN {
	if m != nil {
		return m.Scale
	}
	return nil
}

func (m *Component_SpaceComponent) GetShape() *Shape {
	if m != nil {
		return m.Shape
	}
	return nil
}

type Component_SpaceTimeComponent struct {
	Timestamp            *timestamp.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Space                *Component_SpaceComponent `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Component_SpaceTimeComponent) Reset()         { *m = Component_SpaceTimeComponent{} }
func (m *Component_SpaceTimeComponent) String() string { return proto.CompactTextString(m) }
func (*Component_SpaceTimeComponent) ProtoMessage()    {}
func (*Component_SpaceTimeComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 1}
}

func (m *Component_SpaceTimeComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_SpaceTimeComponent.Unmarshal(m, b)
}
func (m *Component_SpaceTimeComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_SpaceTimeComponent.Marshal(b, m, deterministic)
}
func (m *Component_SpaceTimeComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_SpaceTimeComponent.Merge(m, src)
}
func (m *Component_SpaceTimeComponent) XXX_Size() int {
	return xxx_messageInfo_Component_SpaceTimeComponent.Size(m)
}
func (m *Component_SpaceTimeComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_SpaceTimeComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_SpaceTimeComponent proto.InternalMessageInfo

func (m *Component_SpaceTimeComponent) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Component_SpaceTimeComponent) GetSpace() *Component_SpaceComponent {
	if m != nil {
		return m.Space
	}
	return nil
}

type Component_HealthComponent struct {
	Life                 float64  `protobuf:"fixed64,1,opt,name=life,proto3" json:"life,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_HealthComponent) Reset()         { *m = Component_HealthComponent{} }
func (m *Component_HealthComponent) String() string { return proto.CompactTextString(m) }
func (*Component_HealthComponent) ProtoMessage()    {}
func (*Component_HealthComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 2}
}

func (m *Component_HealthComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_HealthComponent.Unmarshal(m, b)
}
func (m *Component_HealthComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_HealthComponent.Marshal(b, m, deterministic)
}
func (m *Component_HealthComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_HealthComponent.Merge(m, src)
}
func (m *Component_HealthComponent) XXX_Size() int {
	return xxx_messageInfo_Component_HealthComponent.Size(m)
}
func (m *Component_HealthComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_HealthComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_HealthComponent proto.InternalMessageInfo

func (m *Component_HealthComponent) GetLife() float64 {
	if m != nil {
		return m.Life
	}
	return 0
}

type Component_SpeedComponent struct {
	MoveSpeed            float64  `protobuf:"fixed64,1,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_SpeedComponent) Reset()         { *m = Component_SpeedComponent{} }
func (m *Component_SpeedComponent) String() string { return proto.CompactTextString(m) }
func (*Component_SpeedComponent) ProtoMessage()    {}
func (*Component_SpeedComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 3}
}

func (m *Component_SpeedComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_SpeedComponent.Unmarshal(m, b)
}
func (m *Component_SpeedComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_SpeedComponent.Marshal(b, m, deterministic)
}
func (m *Component_SpeedComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_SpeedComponent.Merge(m, src)
}
func (m *Component_SpeedComponent) XXX_Size() int {
	return xxx_messageInfo_Component_SpeedComponent.Size(m)
}
func (m *Component_SpeedComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_SpeedComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_SpeedComponent proto.InternalMessageInfo

func (m *Component_SpeedComponent) GetMoveSpeed() float64 {
	if m != nil {
		return m.MoveSpeed
	}
	return 0
}

type Component_TargetComponent struct {
	Target               *protometry.VectorN `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Component_TargetComponent) Reset()         { *m = Component_TargetComponent{} }
func (m *Component_TargetComponent) String() string { return proto.CompactTextString(m) }
func (*Component_TargetComponent) ProtoMessage()    {}
func (*Component_TargetComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 4}
}

func (m *Component_TargetComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_TargetComponent.Unmarshal(m, b)
}
func (m *Component_TargetComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_TargetComponent.Marshal(b, m, deterministic)
}
func (m *Component_TargetComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_TargetComponent.Merge(m, src)
}
func (m *Component_TargetComponent) XXX_Size() int {
	return xxx_messageInfo_Component_TargetComponent.Size(m)
}
func (m *Component_TargetComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_TargetComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_TargetComponent proto.InternalMessageInfo

func (m *Component_TargetComponent) GetTarget() *protometry.VectorN {
	if m != nil {
		return m.Target
	}
	return nil
}

type Component_RenderComponent struct {
	Red                  float32  `protobuf:"fixed32,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                float32  `protobuf:"fixed32,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 float32  `protobuf:"fixed32,3,opt,name=blue,proto3" json:"blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_RenderComponent) Reset()         { *m = Component_RenderComponent{} }
func (m *Component_RenderComponent) String() string { return proto.CompactTextString(m) }
func (*Component_RenderComponent) ProtoMessage()    {}
func (*Component_RenderComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 5}
}

func (m *Component_RenderComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_RenderComponent.Unmarshal(m, b)
}
func (m *Component_RenderComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_RenderComponent.Marshal(b, m, deterministic)
}
func (m *Component_RenderComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_RenderComponent.Merge(m, src)
}
func (m *Component_RenderComponent) XXX_Size() int {
	return xxx_messageInfo_Component_RenderComponent.Size(m)
}
func (m *Component_RenderComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_RenderComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_RenderComponent proto.InternalMessageInfo

func (m *Component_RenderComponent) GetRed() float32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Component_RenderComponent) GetGreen() float32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Component_RenderComponent) GetBlue() float32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

// Acts as a sort of tag, see if we could do something cleaner
type Component_BehaviourTypeComponent struct {
	BehaviourType        Component_BehaviourTypeComponent_BehaviourType `protobuf:"varint,1,opt,name=behaviour_type,json=behaviourType,proto3,enum=erutan.Component_BehaviourTypeComponent_BehaviourType" json:"behaviour_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Component_BehaviourTypeComponent) Reset()         { *m = Component_BehaviourTypeComponent{} }
func (m *Component_BehaviourTypeComponent) String() string { return proto.CompactTextString(m) }
func (*Component_BehaviourTypeComponent) ProtoMessage()    {}
func (*Component_BehaviourTypeComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 6}
}

func (m *Component_BehaviourTypeComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Unmarshal(m, b)
}
func (m *Component_BehaviourTypeComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Marshal(b, m, deterministic)
}
func (m *Component_BehaviourTypeComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_BehaviourTypeComponent.Merge(m, src)
}
func (m *Component_BehaviourTypeComponent) XXX_Size() int {
	return xxx_messageInfo_Component_BehaviourTypeComponent.Size(m)
}
func (m *Component_BehaviourTypeComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_BehaviourTypeComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_BehaviourTypeComponent proto.InternalMessageInfo

func (m *Component_BehaviourTypeComponent) GetBehaviourType() Component_BehaviourTypeComponent_BehaviourType {
	if m != nil {
		return m.BehaviourType
	}
	return Component_BehaviourTypeComponent_ANY
}

type Component_PhysicsComponent struct {
	UseGravity           bool     `protobuf:"varint,1,opt,name=use_gravity,json=useGravity,proto3" json:"use_gravity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component_PhysicsComponent) Reset()         { *m = Component_PhysicsComponent{} }
func (m *Component_PhysicsComponent) String() string { return proto.CompactTextString(m) }
func (*Component_PhysicsComponent) ProtoMessage()    {}
func (*Component_PhysicsComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{4, 7}
}

func (m *Component_PhysicsComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component_PhysicsComponent.Unmarshal(m, b)
}
func (m *Component_PhysicsComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component_PhysicsComponent.Marshal(b, m, deterministic)
}
func (m *Component_PhysicsComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component_PhysicsComponent.Merge(m, src)
}
func (m *Component_PhysicsComponent) XXX_Size() int {
	return xxx_messageInfo_Component_PhysicsComponent.Size(m)
}
func (m *Component_PhysicsComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_Component_PhysicsComponent.DiscardUnknown(m)
}

var xxx_messageInfo_Component_PhysicsComponent proto.InternalMessageInfo

func (m *Component_PhysicsComponent) GetUseGravity() bool {
	if m != nil {
		return m.UseGravity
	}
	return false
}

type Packet struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Packet_CreateEntity
	//	*Packet_UpdateEntity
	//	*Packet_UpdatePosition
	//	*Packet_UpdateRotation
	//	*Packet_DestroyEntity
	//	*Packet_UpdateAnimal
	//	*Packet_UpdateParameters
	Type                 isPacket_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isPacket_Type interface {
	isPacket_Type()
}

type Packet_CreateEntity struct {
	CreateEntity *Packet_CreateEntityPacket `protobuf:"bytes,2,opt,name=create_entity,json=createEntity,proto3,oneof"`
}

type Packet_UpdateEntity struct {
	UpdateEntity *Packet_UpdateEntityPacket `protobuf:"bytes,3,opt,name=update_entity,json=updateEntity,proto3,oneof"`
}

type Packet_UpdatePosition struct {
	UpdatePosition *Packet_UpdatePositionPacket `protobuf:"bytes,4,opt,name=update_position,json=updatePosition,proto3,oneof"`
}

type Packet_UpdateRotation struct {
	UpdateRotation *Packet_UpdateRotationPacket `protobuf:"bytes,5,opt,name=update_rotation,json=updateRotation,proto3,oneof"`
}

type Packet_DestroyEntity struct {
	DestroyEntity *Packet_DestroyEntityPacket `protobuf:"bytes,6,opt,name=destroy_entity,json=destroyEntity,proto3,oneof"`
}

type Packet_UpdateAnimal struct {
	UpdateAnimal *Packet_UpdateAnimalPacket `protobuf:"bytes,7,opt,name=update_animal,json=updateAnimal,proto3,oneof"`
}

type Packet_UpdateParameters struct {
	UpdateParameters *Packet_UpdateParametersPacket `protobuf:"bytes,8,opt,name=update_parameters,json=updateParameters,proto3,oneof"`
}

func (*Packet_CreateEntity) isPacket_Type() {}

func (*Packet_UpdateEntity) isPacket_Type() {}

func (*Packet_UpdatePosition) isPacket_Type() {}

func (*Packet_UpdateRotation) isPacket_Type() {}

func (*Packet_DestroyEntity) isPacket_Type() {}

func (*Packet_UpdateAnimal) isPacket_Type() {}

func (*Packet_UpdateParameters) isPacket_Type() {}

func (m *Packet) GetType() isPacket_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Packet) GetCreateEntity() *Packet_CreateEntityPacket {
	if x, ok := m.GetType().(*Packet_CreateEntity); ok {
		return x.CreateEntity
	}
	return nil
}

func (m *Packet) GetUpdateEntity() *Packet_UpdateEntityPacket {
	if x, ok := m.GetType().(*Packet_UpdateEntity); ok {
		return x.UpdateEntity
	}
	return nil
}

func (m *Packet) GetUpdatePosition() *Packet_UpdatePositionPacket {
	if x, ok := m.GetType().(*Packet_UpdatePosition); ok {
		return x.UpdatePosition
	}
	return nil
}

func (m *Packet) GetUpdateRotation() *Packet_UpdateRotationPacket {
	if x, ok := m.GetType().(*Packet_UpdateRotation); ok {
		return x.UpdateRotation
	}
	return nil
}

func (m *Packet) GetDestroyEntity() *Packet_DestroyEntityPacket {
	if x, ok := m.GetType().(*Packet_DestroyEntity); ok {
		return x.DestroyEntity
	}
	return nil
}

func (m *Packet) GetUpdateAnimal() *Packet_UpdateAnimalPacket {
	if x, ok := m.GetType().(*Packet_UpdateAnimal); ok {
		return x.UpdateAnimal
	}
	return nil
}

func (m *Packet) GetUpdateParameters() *Packet_UpdateParametersPacket {
	if x, ok := m.GetType().(*Packet_UpdateParameters); ok {
		return x.UpdateParameters
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_CreateEntity)(nil),
		(*Packet_UpdateEntity)(nil),
		(*Packet_UpdatePosition)(nil),
		(*Packet_UpdateRotation)(nil),
		(*Packet_DestroyEntity)(nil),
		(*Packet_UpdateAnimal)(nil),
		(*Packet_UpdateParameters)(nil),
	}
}

type Packet_CreateEntityPacket struct {
	EntityId             uint64       `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components           []*Component `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Packet_CreateEntityPacket) Reset()         { *m = Packet_CreateEntityPacket{} }
func (m *Packet_CreateEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_CreateEntityPacket) ProtoMessage()    {}
func (*Packet_CreateEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 0}
}

func (m *Packet_CreateEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_CreateEntityPacket.Unmarshal(m, b)
}
func (m *Packet_CreateEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_CreateEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_CreateEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_CreateEntityPacket.Merge(m, src)
}
func (m *Packet_CreateEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_CreateEntityPacket.Size(m)
}
func (m *Packet_CreateEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_CreateEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_CreateEntityPacket proto.InternalMessageInfo

func (m *Packet_CreateEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_CreateEntityPacket) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

type Packet_UpdateEntityPacket struct {
	EntityId             uint64       `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components           []*Component `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Packet_UpdateEntityPacket) Reset()         { *m = Packet_UpdateEntityPacket{} }
func (m *Packet_UpdateEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateEntityPacket) ProtoMessage()    {}
func (*Packet_UpdateEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 1}
}

func (m *Packet_UpdateEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateEntityPacket.Merge(m, src)
}
func (m *Packet_UpdateEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateEntityPacket.Size(m)
}
func (m *Packet_UpdateEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateEntityPacket proto.InternalMessageInfo

func (m *Packet_UpdateEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateEntityPacket) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

type Packet_UpdatePositionPacket struct {
	EntityId             uint64              `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Position             *protometry.VectorN `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Packet_UpdatePositionPacket) Reset()         { *m = Packet_UpdatePositionPacket{} }
func (m *Packet_UpdatePositionPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdatePositionPacket) ProtoMessage()    {}
func (*Packet_UpdatePositionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 2}
}

func (m *Packet_UpdatePositionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Unmarshal(m, b)
}
func (m *Packet_UpdatePositionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdatePositionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdatePositionPacket.Merge(m, src)
}
func (m *Packet_UpdatePositionPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdatePositionPacket.Size(m)
}
func (m *Packet_UpdatePositionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdatePositionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdatePositionPacket proto.InternalMessageInfo

func (m *Packet_UpdatePositionPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdatePositionPacket) GetPosition() *protometry.VectorN {
	if m != nil {
		return m.Position
	}
	return nil
}

type Packet_UpdateRotationPacket struct {
	EntityId             uint64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Rotation             *protometry.QuaternionN `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Packet_UpdateRotationPacket) Reset()         { *m = Packet_UpdateRotationPacket{} }
func (m *Packet_UpdateRotationPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateRotationPacket) ProtoMessage()    {}
func (*Packet_UpdateRotationPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 3}
}

func (m *Packet_UpdateRotationPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateRotationPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateRotationPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateRotationPacket.Merge(m, src)
}
func (m *Packet_UpdateRotationPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateRotationPacket.Size(m)
}
func (m *Packet_UpdateRotationPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateRotationPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateRotationPacket proto.InternalMessageInfo

func (m *Packet_UpdateRotationPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateRotationPacket) GetRotation() *protometry.QuaternionN {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Packet_DestroyEntityPacket struct {
	EntityId             uint64   `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_DestroyEntityPacket) Reset()         { *m = Packet_DestroyEntityPacket{} }
func (m *Packet_DestroyEntityPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_DestroyEntityPacket) ProtoMessage()    {}
func (*Packet_DestroyEntityPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 4}
}

func (m *Packet_DestroyEntityPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Unmarshal(m, b)
}
func (m *Packet_DestroyEntityPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Marshal(b, m, deterministic)
}
func (m *Packet_DestroyEntityPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_DestroyEntityPacket.Merge(m, src)
}
func (m *Packet_DestroyEntityPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_DestroyEntityPacket.Size(m)
}
func (m *Packet_DestroyEntityPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_DestroyEntityPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_DestroyEntityPacket proto.InternalMessageInfo

func (m *Packet_DestroyEntityPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type Packet_UpdateAnimalPacket struct {
	EntityId             uint64   `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Life                 float64  `protobuf:"fixed64,2,opt,name=life,proto3" json:"life,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_UpdateAnimalPacket) Reset()         { *m = Packet_UpdateAnimalPacket{} }
func (m *Packet_UpdateAnimalPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateAnimalPacket) ProtoMessage()    {}
func (*Packet_UpdateAnimalPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 5}
}

func (m *Packet_UpdateAnimalPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateAnimalPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateAnimalPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateAnimalPacket.Merge(m, src)
}
func (m *Packet_UpdateAnimalPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateAnimalPacket.Size(m)
}
func (m *Packet_UpdateAnimalPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateAnimalPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateAnimalPacket proto.InternalMessageInfo

func (m *Packet_UpdateAnimalPacket) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Packet_UpdateAnimalPacket) GetLife() float64 {
	if m != nil {
		return m.Life
	}
	return 0
}

type Packet_UpdateParametersPacket struct {
	Parameters           []*Packet_UpdateParametersPacket_Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Packet_UpdateParametersPacket) Reset()         { *m = Packet_UpdateParametersPacket{} }
func (m *Packet_UpdateParametersPacket) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateParametersPacket) ProtoMessage()    {}
func (*Packet_UpdateParametersPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 6}
}

func (m *Packet_UpdateParametersPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Unmarshal(m, b)
}
func (m *Packet_UpdateParametersPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateParametersPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateParametersPacket.Merge(m, src)
}
func (m *Packet_UpdateParametersPacket) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateParametersPacket.Size(m)
}
func (m *Packet_UpdateParametersPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateParametersPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateParametersPacket proto.InternalMessageInfo

func (m *Packet_UpdateParametersPacket) GetParameters() []*Packet_UpdateParametersPacket_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Packet_UpdateParametersPacket_Parameter struct {
	// Types that are valid to be assigned to Type:
	//	*Packet_UpdateParametersPacket_Parameter_TimeScale
	Type                 isPacket_UpdateParametersPacket_Parameter_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Packet_UpdateParametersPacket_Parameter) Reset() {
	*m = Packet_UpdateParametersPacket_Parameter{}
}
func (m *Packet_UpdateParametersPacket_Parameter) String() string { return proto.CompactTextString(m) }
func (*Packet_UpdateParametersPacket_Parameter) ProtoMessage()    {}
func (*Packet_UpdateParametersPacket_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_647af75c89a25519, []int{5, 6, 0}
}

func (m *Packet_UpdateParametersPacket_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Unmarshal(m, b)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Marshal(b, m, deterministic)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Merge(m, src)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_Size() int {
	return xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.Size(m)
}
func (m *Packet_UpdateParametersPacket_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_UpdateParametersPacket_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_UpdateParametersPacket_Parameter proto.InternalMessageInfo

type isPacket_UpdateParametersPacket_Parameter_Type interface {
	isPacket_UpdateParametersPacket_Parameter_Type()
}

type Packet_UpdateParametersPacket_Parameter_TimeScale struct {
	TimeScale float64 `protobuf:"fixed64,1,opt,name=time_scale,json=timeScale,proto3,oneof"`
}

func (*Packet_UpdateParametersPacket_Parameter_TimeScale) isPacket_UpdateParametersPacket_Parameter_Type() {
}

func (m *Packet_UpdateParametersPacket_Parameter) GetType() isPacket_UpdateParametersPacket_Parameter_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Packet_UpdateParametersPacket_Parameter) GetTimeScale() float64 {
	if x, ok := m.GetType().(*Packet_UpdateParametersPacket_Parameter_TimeScale); ok {
		return x.TimeScale
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet_UpdateParametersPacket_Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_UpdateParametersPacket_Parameter_TimeScale)(nil),
	}
}

func init() {
	proto.RegisterEnum("erutan.Component_BehaviourTypeComponent_BehaviourType", Component_BehaviourTypeComponent_BehaviourType_name, Component_BehaviourTypeComponent_BehaviourType_value)
	proto.RegisterType((*Metadata)(nil), "erutan.Metadata")
	proto.RegisterType((*Shape)(nil), "erutan.Shape")
	proto.RegisterType((*Collider)(nil), "erutan.Collider")
	proto.RegisterType((*Ellipse)(nil), "erutan.Ellipse")
	proto.RegisterType((*Component)(nil), "erutan.Component")
	proto.RegisterType((*Component_SpaceComponent)(nil), "erutan.Component.SpaceComponent")
	proto.RegisterType((*Component_SpaceTimeComponent)(nil), "erutan.Component.SpaceTimeComponent")
	proto.RegisterType((*Component_HealthComponent)(nil), "erutan.Component.HealthComponent")
	proto.RegisterType((*Component_SpeedComponent)(nil), "erutan.Component.SpeedComponent")
	proto.RegisterType((*Component_TargetComponent)(nil), "erutan.Component.TargetComponent")
	proto.RegisterType((*Component_RenderComponent)(nil), "erutan.Component.RenderComponent")
	proto.RegisterType((*Component_BehaviourTypeComponent)(nil), "erutan.Component.BehaviourTypeComponent")
	proto.RegisterType((*Component_PhysicsComponent)(nil), "erutan.Component.PhysicsComponent")
	proto.RegisterType((*Packet)(nil), "erutan.Packet")
	proto.RegisterType((*Packet_CreateEntityPacket)(nil), "erutan.Packet.CreateEntityPacket")
	proto.RegisterType((*Packet_UpdateEntityPacket)(nil), "erutan.Packet.UpdateEntityPacket")
	proto.RegisterType((*Packet_UpdatePositionPacket)(nil), "erutan.Packet.UpdatePositionPacket")
	proto.RegisterType((*Packet_UpdateRotationPacket)(nil), "erutan.Packet.UpdateRotationPacket")
	proto.RegisterType((*Packet_DestroyEntityPacket)(nil), "erutan.Packet.DestroyEntityPacket")
	proto.RegisterType((*Packet_UpdateAnimalPacket)(nil), "erutan.Packet.UpdateAnimalPacket")
	proto.RegisterType((*Packet_UpdateParametersPacket)(nil), "erutan.Packet.UpdateParametersPacket")
	proto.RegisterType((*Packet_UpdateParametersPacket_Parameter)(nil), "erutan.Packet.UpdateParametersPacket.Parameter")
}

func init() {
	proto.RegisterFile("protobuf/erutan.proto", fileDescriptor_647af75c89a25519)
}

var fileDescriptor_647af75c89a25519 = []byte{
	// 1084 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x29, 0x8b, 0x96, 0xc6, 0xb5, 0xac, 0x6c, 0xd3, 0x80, 0x60, 0xd1, 0xda, 0x51, 0x6a,
	0xc0, 0x87, 0x40, 0x4e, 0x15, 0xc3, 0x30, 0x5a, 0xa0, 0x80, 0xe3, 0x08, 0xb1, 0xd1, 0x5a, 0x71,
	0x68, 0x35, 0x40, 0x0f, 0x85, 0xb0, 0x26, 0x27, 0x36, 0x11, 0x4a, 0x64, 0x97, 0x4b, 0xc1, 0xfa,
	0x81, 0xfe, 0x41, 0xcf, 0xbd, 0xf5, 0xd6, 0x73, 0x3f, 0xa6, 0x3f, 0x53, 0xec, 0x2e, 0x97, 0xa1,
	0x28, 0x5a, 0x11, 0xda, 0x9e, 0xc4, 0x9d, 0x7d, 0xf3, 0x66, 0x76, 0xe6, 0xcd, 0xae, 0xe0, 0xb3,
	0x98, 0x45, 0x3c, 0xba, 0x4e, 0xdf, 0x1d, 0x20, 0x4b, 0x39, 0x9d, 0x74, 0xe5, 0x9a, 0x58, 0x6a,
	0xe5, 0xec, 0xdc, 0x44, 0xd1, 0x4d, 0x88, 0x07, 0x39, 0x8a, 0x07, 0x63, 0x4c, 0x38, 0x1d, 0xc7,
	0x0a, 0xe8, 0x3c, 0xce, 0x77, 0xe4, 0xc7, 0x18, 0x39, 0x9b, 0x1d, 0x4c, 0xd1, 0xe3, 0x11, 0xcb,
	0xb8, 0x9c, 0xbd, 0x2a, 0xc8, 0x2f, 0x29, 0xe5, 0xc8, 0x26, 0x41, 0x34, 0xc9, 0x60, 0x9d, 0x97,
	0xd0, 0xb8, 0x40, 0x4e, 0x7d, 0xca, 0x29, 0x39, 0x86, 0x66, 0x1e, 0xc8, 0x36, 0x76, 0x8d, 0xfd,
	0xcd, 0x9e, 0xd3, 0x55, 0xa9, 0x74, 0x35, 0x5b, 0x77, 0xa8, 0x11, 0xee, 0x07, 0x70, 0xe7, 0x2f,
	0x03, 0xea, 0x57, 0xb7, 0x34, 0x46, 0x72, 0x04, 0x8d, 0x29, 0x32, 0x1e, 0x78, 0x98, 0xd8, 0xe6,
	0x6e, 0x4d, 0x52, 0x14, 0xcf, 0x28, 0xf3, 0xe8, 0xbe, 0x95, 0xa9, 0x0e, 0xdc, 0x1c, 0x4b, 0x08,
	0xac, 0x73, 0x16, 0x24, 0x76, 0x6d, 0xb7, 0xb6, 0x5f, 0x77, 0xe5, 0x37, 0x39, 0x84, 0x8d, 0x49,
	0xc4, 0xc6, 0x34, 0x4c, 0xec, 0xf5, 0x8f, 0x52, 0x69, 0x28, 0x79, 0x0a, 0xb5, 0x74, 0x9a, 0xd8,
	0xf5, 0x8f, 0x7a, 0x08, 0x58, 0x07, 0xa0, 0x71, 0x1a, 0x85, 0x61, 0xe0, 0x23, 0xeb, 0x9c, 0xc3,
	0x46, 0x3f, 0x0c, 0x83, 0x38, 0x41, 0xd2, 0x02, 0xd3, 0xbb, 0x93, 0x35, 0x30, 0x5c, 0xd3, 0xbb,
	0x93, 0xeb, 0x99, 0x6d, 0x66, 0xeb, 0x99, 0x58, 0xb3, 0x3b, 0xbb, 0xa6, 0xd6, 0x4c, 0xee, 0xb3,
	0x99, 0xbd, 0x9e, 0xad, 0x67, 0x9d, 0xdf, 0x00, 0x9a, 0xa7, 0xd1, 0x38, 0x8e, 0x26, 0x38, 0xe1,
	0xe4, 0x18, 0xea, 0x49, 0x4c, 0x3d, 0xcc, 0x8a, 0xba, 0xab, 0x93, 0xca, 0x11, 0xdd, 0x2b, 0xb1,
	0x9d, 0x2f, 0xcf, 0xd6, 0x5c, 0xe5, 0x40, 0xfa, 0x00, 0xf2, 0x63, 0x24, 0x6a, 0x2d, 0xe3, 0x6f,
	0xf6, 0xbe, 0xba, 0xc7, 0x5d, 0x74, 0xa6, 0x48, 0xd1, 0x4c, 0xb4, 0x95, 0x7c, 0x0b, 0xd6, 0x2d,
	0xd2, 0x90, 0xdf, 0xca, 0x94, 0x37, 0x7b, 0x8f, 0x17, 0x29, 0xce, 0xe4, 0x7e, 0xd1, 0x3f, 0x73,
	0x51, 0xd9, 0x23, 0xfa, 0xf2, 0x78, 0xf7, 0x64, 0x8f, 0xe8, 0x97, 0xb2, 0x47, 0xf4, 0x45, 0x58,
	0x86, 0x13, 0x1f, 0x99, 0x5d, 0xbf, 0x2f, 0xac, 0x2b, 0xf7, 0xe7, 0xc2, 0x2a, 0x17, 0xf2, 0x06,
	0x5a, 0xd7, 0x78, 0x4b, 0xa7, 0x41, 0x94, 0xb2, 0x11, 0x9f, 0xc5, 0x68, 0x5b, 0x92, 0x64, 0x7f,
	0x91, 0xe4, 0x85, 0xc6, 0x0d, 0x67, 0xf1, 0x5c, 0x09, 0xb6, 0xae, 0x8b, 0x3b, 0xe4, 0x3b, 0xd8,
	0x88, 0x6f, 0x67, 0x49, 0xe0, 0x25, 0xf6, 0x86, 0xe4, 0xea, 0x2c, 0x72, 0x5d, 0x2a, 0x40, 0x91,
	0x45, 0x3b, 0x39, 0x7f, 0x1b, 0xd0, 0x9a, 0xef, 0x94, 0xd0, 0x7b, 0x1c, 0x25, 0x01, 0x0f, 0xa2,
	0x49, 0x3e, 0x32, 0x4b, 0xf4, 0xae, 0xb1, 0xe4, 0x1b, 0x68, 0xb0, 0x88, 0x53, 0xe9, 0xa7, 0xda,
	0xfa, 0x65, 0x85, 0xdf, 0x9b, 0x7c, 0x5e, 0x07, 0x6e, 0x8e, 0x27, 0xcf, 0xa0, 0x9e, 0x78, 0x34,
	0xc4, 0xac, 0x99, 0xcb, 0x02, 0x2a, 0x20, 0x79, 0x02, 0xf5, 0x44, 0x8c, 0x67, 0xd6, 0xc2, 0x2d,
	0xed, 0x21, 0x67, 0xd6, 0x55, 0x7b, 0xce, 0xaf, 0x06, 0x90, 0x45, 0x21, 0xfd, 0xfb, 0x5b, 0x81,
	0x1c, 0x69, 0xd9, 0x9b, 0xab, 0xc9, 0x3e, 0x13, 0xbd, 0xb3, 0x07, 0xdb, 0x25, 0x35, 0x8a, 0xeb,
	0x21, 0x0c, 0xde, 0x61, 0x36, 0x91, 0xf2, 0xdb, 0x39, 0x10, 0xcd, 0x28, 0x0a, 0x8f, 0x7c, 0x01,
	0x30, 0x8e, 0xa6, 0x38, 0x52, 0x72, 0x55, 0xd8, 0xa6, 0xb0, 0x48, 0x9c, 0xd3, 0x87, 0xed, 0x21,
	0x65, 0x37, 0xc8, 0x3f, 0x78, 0xf4, 0xc0, 0xe2, 0xd2, 0xb4, 0x42, 0xf3, 0x32, 0xa4, 0x73, 0x01,
	0xdb, 0x25, 0xd5, 0x92, 0x36, 0xd4, 0x58, 0x16, 0xd1, 0x74, 0xc5, 0x27, 0x79, 0x08, 0xf5, 0x1b,
	0x86, 0xa8, 0x9a, 0x6b, 0xba, 0x6a, 0x21, 0x8e, 0x71, 0x1d, 0xa6, 0xaa, 0x71, 0xa6, 0x2b, 0xbf,
	0x9d, 0x3f, 0x0d, 0x78, 0x54, 0x2d, 0x60, 0xf2, 0xf3, 0xc2, 0x08, 0x88, 0x08, 0xad, 0xde, 0xd1,
	0xaa, 0x23, 0x30, 0x6f, 0x2e, 0x8d, 0x43, 0xe7, 0x10, 0xb6, 0xe6, 0xf6, 0xc9, 0x06, 0xd4, 0x4e,
	0x06, 0x3f, 0xb5, 0xd7, 0x08, 0x80, 0x75, 0x32, 0x38, 0xbf, 0x38, 0xf9, 0xa1, 0x6d, 0x90, 0x16,
	0xc0, 0xdb, 0xfe, 0xab, 0xfe, 0xf0, 0x64, 0x78, 0xfe, 0x7a, 0xd0, 0x36, 0x9d, 0xe7, 0xd0, 0x2e,
	0xcf, 0x08, 0xd9, 0x81, 0xcd, 0x34, 0xc1, 0xd1, 0x0d, 0xa3, 0xd3, 0x80, 0xcf, 0x64, 0x96, 0x0d,
	0x17, 0xd2, 0x04, 0x5f, 0x29, 0xcb, 0x0b, 0x0b, 0xd6, 0x45, 0xfe, 0x9d, 0x3f, 0x00, 0xac, 0x4b,
	0xea, 0xbd, 0x47, 0x4e, 0x9e, 0x42, 0x63, 0x9c, 0xbd, 0x3c, 0x59, 0xf1, 0xdb, 0xfa, 0x58, 0xfa,
	0x45, 0x72, 0x73, 0x04, 0x39, 0x83, 0x2d, 0x8f, 0x21, 0xe5, 0x38, 0xc2, 0x09, 0x17, 0x31, 0xcc,
	0xf9, 0x1b, 0x45, 0x91, 0x76, 0x4f, 0x25, 0xa6, 0x2f, 0x21, 0xca, 0x74, 0xb6, 0xe6, 0x7e, 0xe2,
	0x15, 0xac, 0x82, 0x29, 0x8d, 0xfd, 0x02, 0x53, 0xad, 0x92, 0xe9, 0x47, 0x89, 0x29, 0x33, 0xa5,
	0x05, 0x2b, 0x19, 0xc0, 0x76, 0xc6, 0x94, 0x5f, 0x01, 0x6a, 0xbe, 0x9e, 0x54, 0x72, 0x5d, 0x66,
	0xa0, 0x9c, 0xad, 0x95, 0xce, 0xd9, 0x0b, 0x7c, 0xf9, 0xd5, 0x50, 0x5f, 0xc2, 0xe7, 0x66, 0xa0,
	0x32, 0x9f, 0xb6, 0x93, 0xef, 0xa1, 0xe5, 0x63, 0xc2, 0x59, 0x34, 0xd3, 0x47, 0xb5, 0xe6, 0x6f,
	0xbd, 0x8c, 0xee, 0xa5, 0x02, 0x95, 0xce, 0xba, 0xe5, 0x17, 0xcd, 0x85, 0xb2, 0xd1, 0x49, 0x30,
	0xa6, 0x61, 0x76, 0x83, 0x56, 0x97, 0xed, 0x44, 0x42, 0xca, 0x65, 0x53, 0x56, 0x32, 0x84, 0x07,
	0xba, 0x6c, 0x94, 0xd1, 0x31, 0x72, 0x64, 0x89, 0xdd, 0x90, 0x6c, 0x7b, 0xd5, 0x85, 0xcb, 0x61,
	0x39, 0x63, 0x3b, 0x2d, 0xed, 0x38, 0x3e, 0x90, 0xc5, 0xe6, 0x93, 0xcf, 0xa1, 0xa9, 0x8e, 0x3e,
	0x0a, 0xd4, 0x78, 0xae, 0xbb, 0x0d, 0x65, 0x38, 0xf7, 0xc9, 0xd7, 0x00, 0x9e, 0x96, 0xb0, 0xfe,
	0xb7, 0xf2, 0x60, 0x61, 0xb4, 0xdc, 0x02, 0x48, 0x44, 0x59, 0x14, 0xc6, 0xff, 0x1e, 0xe5, 0x3d,
	0x3c, 0xac, 0x92, 0xcc, 0xf2, 0x38, 0xc5, 0x97, 0xc8, 0x5c, 0xfd, 0x25, 0x72, 0x22, 0x1d, 0x6c,
	0x5e, 0x4f, 0xcb, 0x83, 0xfd, 0x87, 0xe7, 0xcb, 0xe9, 0xc1, 0xa7, 0x15, 0x8a, 0x5b, 0x1a, 0xcf,
	0xe9, 0xeb, 0xba, 0x17, 0x95, 0xb5, 0x3c, 0x45, 0xfd, 0x64, 0x98, 0x85, 0x27, 0xe3, 0x77, 0x03,
	0x1e, 0x55, 0x6b, 0x8a, 0xbc, 0x06, 0x28, 0xc8, 0xd1, 0x90, 0x6d, 0x3a, 0x58, 0x49, 0x8e, 0xdd,
	0xdc, 0xe0, 0x16, 0x28, 0x9c, 0x43, 0x68, 0xe6, 0x1b, 0x64, 0x07, 0x40, 0xbc, 0x8b, 0x23, 0xf5,
	0x6e, 0xcb, 0x97, 0x49, 0xfc, 0x43, 0x13, 0xb6, 0x2b, 0x61, 0xd2, 0x17, 0xa4, 0xfe, 0xed, 0x1d,
	0x83, 0xd5, 0x97, 0xb1, 0x49, 0x17, 0xac, 0x2b, 0xce, 0x90, 0x8e, 0x49, 0x6b, 0x3e, 0x1d, 0xa7,
	0xb4, 0xee, 0xac, 0xed, 0x1b, 0xcf, 0x8c, 0x4b, 0xf3, 0xda, 0x92, 0x2d, 0x78, 0xfe, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0x75, 0xc0, 0xf4, 0x66, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ErutanClient is the client API for Erutan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ErutanClient interface {
	//
	//Blabla
	Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error)
}

type erutanClient struct {
	cc grpc.ClientConnInterface
}

func NewErutanClient(cc grpc.ClientConnInterface) ErutanClient {
	return &erutanClient{cc}
}

func (c *erutanClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Erutan_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Erutan_serviceDesc.Streams[0], "/erutan.Erutan/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &erutanStreamClient{stream}
	return x, nil
}

type Erutan_StreamClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type erutanStreamClient struct {
	grpc.ClientStream
}

func (x *erutanStreamClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *erutanStreamClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ErutanServer is the server API for Erutan service.
type ErutanServer interface {
	//
	//Blabla
	Stream(Erutan_StreamServer) error
}

// UnimplementedErutanServer can be embedded to have forward compatible implementations.
type UnimplementedErutanServer struct {
}

func (*UnimplementedErutanServer) Stream(srv Erutan_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterErutanServer(s *grpc.Server, srv ErutanServer) {
	s.RegisterService(&_Erutan_serviceDesc, srv)
}

func _Erutan_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ErutanServer).Stream(&erutanStreamServer{stream})
}

type Erutan_StreamServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type erutanStreamServer struct {
	grpc.ServerStream
}

func (x *erutanStreamServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *erutanStreamServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Erutan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erutan.Erutan",
	HandlerType: (*ErutanServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Erutan_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/erutan.proto",
}
