// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/protometry/quaternion.proto

package protometry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Quaternion struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	W                    float64  `protobuf:"fixed64,4,opt,name=w,proto3" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quaternion) Reset()         { *m = Quaternion{} }
func (m *Quaternion) String() string { return proto.CompactTextString(m) }
func (*Quaternion) ProtoMessage()    {}
func (*Quaternion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d995d348451e4668, []int{0}
}

func (m *Quaternion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quaternion.Unmarshal(m, b)
}
func (m *Quaternion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quaternion.Marshal(b, m, deterministic)
}
func (m *Quaternion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quaternion.Merge(m, src)
}
func (m *Quaternion) XXX_Size() int {
	return xxx_messageInfo_Quaternion.Size(m)
}
func (m *Quaternion) XXX_DiscardUnknown() {
	xxx_messageInfo_Quaternion.DiscardUnknown(m)
}

var xxx_messageInfo_Quaternion proto.InternalMessageInfo

func (m *Quaternion) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Quaternion) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Quaternion) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Quaternion) GetW() float64 {
	if m != nil {
		return m.W
	}
	return 0
}

func init() {
	proto.RegisterType((*Quaternion)(nil), "protometry.Quaternion")
}

func init() {
	proto.RegisterFile("protobuf/protometry/quaternion.proto", fileDescriptor_d995d348451e4668)
}

var fileDescriptor_d995d348451e4668 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x07, 0x33, 0x72, 0x53, 0x4b, 0x8a, 0x2a, 0xf5, 0x0b, 0x4b, 0x13,
	0x4b, 0x52, 0x8b, 0xf2, 0x32, 0xf3, 0xf3, 0xf4, 0xc0, 0xa2, 0x42, 0x5c, 0x08, 0x49, 0x25, 0x17,
	0x2e, 0xae, 0x40, 0xb8, 0xbc, 0x10, 0x0f, 0x17, 0x63, 0x85, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x63,
	0x10, 0x63, 0x05, 0x88, 0x57, 0x29, 0xc1, 0x04, 0xe1, 0x55, 0x82, 0x78, 0x55, 0x12, 0xcc, 0x10,
	0x5e, 0x15, 0x88, 0x57, 0x2e, 0xc1, 0x02, 0xe1, 0x95, 0x3b, 0xe9, 0x47, 0x29, 0xa4, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x87, 0x64, 0xa4, 0xea, 0x86, 0xa4, 0xe6, 0x15,
	0xe7, 0x57, 0x20, 0x39, 0x63, 0x15, 0x13, 0x57, 0x00, 0x9c, 0x93, 0xc4, 0x06, 0x96, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x25, 0x92, 0x88, 0x01, 0xb1, 0x00, 0x00, 0x00,
}
