// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/protometry/quaternionn.proto

package protometry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuaternionN struct {
	Value                *VectorN `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuaternionN) Reset()         { *m = QuaternionN{} }
func (m *QuaternionN) String() string { return proto.CompactTextString(m) }
func (*QuaternionN) ProtoMessage()    {}
func (*QuaternionN) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d8ab61378949464, []int{0}
}

func (m *QuaternionN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuaternionN.Unmarshal(m, b)
}
func (m *QuaternionN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuaternionN.Marshal(b, m, deterministic)
}
func (m *QuaternionN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuaternionN.Merge(m, src)
}
func (m *QuaternionN) XXX_Size() int {
	return xxx_messageInfo_QuaternionN.Size(m)
}
func (m *QuaternionN) XXX_DiscardUnknown() {
	xxx_messageInfo_QuaternionN.DiscardUnknown(m)
}

var xxx_messageInfo_QuaternionN proto.InternalMessageInfo

func (m *QuaternionN) GetValue() *VectorN {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*QuaternionN)(nil), "protometry.QuaternionN")
}

func init() {
	proto.RegisterFile("protobuf/protometry/quaternionn.proto", fileDescriptor_7d8ab61378949464)
}

var fileDescriptor_7d8ab61378949464 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x07, 0x33, 0x72, 0x53, 0x4b, 0x8a, 0x2a, 0xf5, 0x0b, 0x4b, 0x13,
	0x4b, 0x52, 0x8b, 0xf2, 0x32, 0xf3, 0xf3, 0xf2, 0xf4, 0xc0, 0xc2, 0x42, 0x5c, 0x08, 0x59, 0x29,
	0x45, 0x6c, 0x5a, 0xca, 0x52, 0x93, 0x4b, 0xf2, 0x8b, 0xa0, 0xca, 0x95, 0x2c, 0xb8, 0xb8, 0x03,
	0xe1, 0x66, 0xf8, 0x09, 0x69, 0x72, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x1b, 0x09, 0xeb, 0x21, 0x34, 0xea, 0x85, 0x81, 0x35, 0xfa, 0x05, 0x41, 0x54, 0x38,
	0xe9, 0x47, 0x29, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x87, 0x64,
	0xa4, 0xea, 0x86, 0xa4, 0xe6, 0x15, 0xe7, 0x57, 0x20, 0xd9, 0xb5, 0x8a, 0x89, 0x2b, 0x00, 0xce,
	0x49, 0x62, 0x03, 0x4b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x17, 0x51, 0xfb, 0xc9,
	0x00, 0x00, 0x00,
}
