// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/protometry/vectorn.proto

package protometry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VectorN struct {
	Dimensions           []float64 `protobuf:"fixed64,1,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VectorN) Reset()         { *m = VectorN{} }
func (m *VectorN) String() string { return proto.CompactTextString(m) }
func (*VectorN) ProtoMessage()    {}
func (*VectorN) Descriptor() ([]byte, []int) {
	return fileDescriptor_226d4d79d6561a96, []int{0}
}

func (m *VectorN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorN.Unmarshal(m, b)
}
func (m *VectorN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorN.Marshal(b, m, deterministic)
}
func (m *VectorN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorN.Merge(m, src)
}
func (m *VectorN) XXX_Size() int {
	return xxx_messageInfo_VectorN.Size(m)
}
func (m *VectorN) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorN.DiscardUnknown(m)
}

var xxx_messageInfo_VectorN proto.InternalMessageInfo

func (m *VectorN) GetDimensions() []float64 {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func init() {
	proto.RegisterType((*VectorN)(nil), "protometry.VectorN")
}

func init() {
	proto.RegisterFile("protobuf/protometry/vectorn.proto", fileDescriptor_226d4d79d6561a96)
}

var fileDescriptor_226d4d79d6561a96 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x07, 0x33, 0x72, 0x53, 0x4b, 0x8a, 0x2a, 0xf5, 0xcb, 0x52, 0x93,
	0x4b, 0xf2, 0x8b, 0xf2, 0xf4, 0xc0, 0x42, 0x42, 0x5c, 0x08, 0x19, 0x25, 0x4d, 0x2e, 0xf6, 0x30,
	0xb0, 0xa4, 0x9f, 0x90, 0x1c, 0x17, 0x57, 0x4a, 0x66, 0x6e, 0x6a, 0x5e, 0x71, 0x66, 0x7e, 0x5e,
	0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x63, 0x10, 0x92, 0x88, 0x93, 0x52, 0x94, 0x42, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x48, 0x46, 0xaa, 0x6e, 0x48, 0x6a, 0x5e,
	0x71, 0x7e, 0x05, 0x92, 0x45, 0x49, 0x6c, 0x60, 0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0x20, 0x90, 0x28, 0x86, 0x00, 0x00, 0x00,
}
